require('dotenv').config();
const mongoose = require('mongoose');

// === 1. Connect to MongoDB ===
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
.then(() => console.log('✅ Connected to MongoDB'))
.catch(err => console.error('❌ Connection error:', err));

// === 2. Define Schema ===
const poiSchema = new mongoose.Schema({
    username: String,
    title: String,
    description: String,
    highlightedData: [{
      entity: String,
      url: String
    }],
    poiIndex: Number
  });
  
const POI = mongoose.model('POI', poiSchema);
// === 🧾 Map of dummy to real usernames ===
const usernameMap = {
    user1: "elena",
    user2: "maria",
    user3: "roberto",
    user4: "luca",
    user5: "monica",
    user6: "maria123",
    user7: "christina",
    user8: "elizabeth",
    user9: "rita",
    user10: "usama" // Replace with correct name if needed
  };
  
  // === 🛠️ Update existing usernames in DB ===
  async function updateUsernames() {
    for (const [oldUsername, newUsername] of Object.entries(usernameMap)) {
      const result = await POI.updateMany(
        { username: oldUsername },
        { $set: { username: newUsername.toLowerCase() } }
      );
      console.log(`🔄 Updated ${result.modifiedCount} POIs from ${oldUsername} → ${newUsername}`);
    }
  }
  
// === 3. Sample POIs ===
let samplePOIs = [
  // POIs for user1
  { username: "elena", description: `Camping Wolf - Il Camping Wolf è un campeggio di montagna situato a Civitella Alfedena, borgo nel cuore del Parco Nazionale d'Abruzzo, un'oasi di natura incontaminata a 2 ore di viaggio da Roma e Napoli. Il campeggio offre una vacanza all'insegna dell'immersione totale nella natura, nel silenzio, tra l'ombra delle querce: circa 60 piazzole per tende, camper e caravan/roulotte, tra muretti a secco, fiori selvatici, alberi. Il lago di Barrea si raggiunge in soli 10 minuti di breve e facile escursione a piedi dal campeggio, lungo un sentiero che segue il tracciato dell'antico tratturo che univa questi territori ai pascoli di Puglia e Lucania. Il centro storico di Civitella dista appena 300 m, con negozi di alimentari/minimarket, bar, ristoranti, farmacia, sportello ATM Bancomat, fermata mezzi di trasporto pubblici. I vicini paesi di Villetta Barrea, Barrea, Opi, Pescasseroli, Scanno sono raggiungibili con brevi gite in auto o con mezzi pubblici. Il Camping Wolf è un campeggio in cui il rispetto per la natura ci guida in ogni scelta: dalle architetture ecologiche, alla scelta dei materiali naturali (legno, pietra), agli impianti tecnologici rinnovabili (pannelli solari per l'acqua calda sanitaria, pannelli fotovoltaici per l'elettricità, coibentazione con pannelli in fibra di legno per garantire microclimi miti all'interno degli edifici, erogatori a risparmio idrico per docce, rubinetti), alla selezione di prodotti enogastronomici, biologici e fatti in casa che potete trovare presso il nostro bar/ristoro. Il campeggio è anche frequentato a volte da alcuni animali selvatici del Parco: cervi e cerbiatti, tassi, ricci, volpi, piccoli animali del bosco, ghiri, lucciole, ghiandaie, upupe, picchi, piccoli rapaci e decine di altre specie. I lupi (nostro animale totem, amato simbolo della nostra natura più intima e selvaggia) della vicinissima area faunistica a volte ululano e cantano nelle sere e nelle notti per ricordarci il dono di essere qui, in un contatto raro con i segreti del mondo naturale.` },
  { username: "elena", description: `Historic Centre of Florence - Built on the site of an Etruscan settlement and later the Roman colony of Florentia. Florence is a treasure trove of art, history, and architecture, with masterpieces by Michelangelo, Botticelli, and Leonardo da Vinci. Major attractions include the Florence Cathedral (Duomo), Uffizi Gallery, and Ponte Vecchio. Florence’s historical center is an open-air museum, showcasing the creativity and intellectual achievements of the Renaissance period.` },
  { username: "elena", description: `Rock Drawings in Valcamonica - Home to approximately 300,000 petroglyphs from the Epipaleolithic era to the Middle Ages. The rock carvings provide an exceptional insight into prehistoric life and spiritual practices in Italy. The Valcamonica rock art is one of the largest and most important collections of prehistoric art in Europe, and it has been recognized as a UNESCO World Heritage Site for its cultural significance.` },
  { username: "elena", description: `Vineyard Landscape of Piedmont - Langhe-Roero and Monferrato offer outstanding wine-growing landscapes shaped over centuries. The terraced hillsides and picturesque villages are integral to the cultivation of world-renowned wines such as Barolo and Barbaresco. The vineyard landscape not only embodies agricultural excellence but also reflects a deep connection between local culture, tradition, and the landscape itself.` },
  { username: "elena", description: `Cittadella of Alessandria - A star fort and citadel built in the 18th century, notable for its preserved fortifications. Designed as a military stronghold, the citadel played a significant role in the defense of the region. Its preserved fortifications and impressive architecture make it a valuable example of military architecture from the late Renaissance period.` },
  { username: "elena", description: `City of Vicenza and the Palladian Villas - Protects buildings designed by architect Andrea Palladio. Vicenza is a city that houses some of the most remarkable buildings designed by Palladio. His villas, with their distinctive style blending classical and Renaissance elements, are spread across the surrounding countryside of Vicenza. The city itself features several of his architectural masterpieces, including the Teatro Olimpico and Villa Rotonda.` },
  { username: "elena", description: `Historic Centre of Urbino - A major Renaissance cultural center with intact medieval walls and Ducal Palace. Urbino, a major cultural center during the Renaissance, is known for its well-preserved medieval walls and the Ducal Palace, one of Italy’s finest examples of Renaissance architecture. The city was home to the influential Duke Federico da Montefeltro, whose court attracted leading artists, scholars, and humanists.` },
  { username: "elena", description: `Historic Centre of Rome - Includes landmarks like the Colosseum, Roman Forum, and the Pantheon. Rome is home to some of the most famous landmarks in the world. The city’s historic center is a vast repository of art, architecture, and culture, marking the city as a major center of Western civilization and a religious hub as the home of the Vatican.` },
  { username: "elena", description: `Historic Centre of Naples - One of the oldest cities in Europe, with a rich mixture of Greek, Roman, and medieval heritage. Naples is home to landmarks such as the Royal Palace of Naples, Castel dell'Ovo, and the ancient Roman city of Pompeii, located just outside the city. Its history spans over 2,800 years and is marked by a unique blend of cultures and civilizations.` },
  { username: "elena", description: `Sassi and the Park of Rupestrian Churches of Matera - Known for ancient cave dwellings and rock-hewn churches. Matera is renowned for its ancient cave dwellings and rock-hewn churches, which date back to the Paleolithic period. The Sassi district of Matera consists of ancient stone dwellings carved into the limestone cliffs, forming one of the world’s oldest continuously inhabited settlements.` },

  // POIs for user2
  { 
    username: "maria", 
    description: `City of Verona - Verona is renowned for its well-preserved Roman heritage and its association with Shakespeare's famous tragedy "Romeo and Juliet." The city boasts a remarkable Roman amphitheater, known as the Arena di Verona, which is still used for opera performances. The town's charm also lies in its medieval and Renaissance architecture, with narrow streets, beautiful piazzas, and iconic landmarks such as Juliet’s house with the famous balcony.`
  },
  { 
    username: "maria", 
    description: `Late Baroque Towns of Val di Noto - This UNESCO World Heritage site comprises several towns in southeastern Sicily, including Noto, Modica, Ragusa, and others, rebuilt in the late 17th and early 18th centuries following the devastating earthquake of 1693. The towns are renowned for their magnificent Baroque architecture, characterized by ornate facades, intricate carvings, and expansive public squares, making them a spectacular example of late Baroque urbanism.`
  },
  { 
    username: "maria", 
    description: `Medici Villas and Gardens in Tuscany - The Medici Villas, a series of Renaissance-era villas scattered throughout Tuscany, showcase the Medici family's power and wealth during the Renaissance period. These villas are celebrated for their architectural grandeur and their stunning gardens, designed to represent the harmony between nature and human creativity. Notable villas include Villa di Castello and Villa La Petraia, which boast lush gardens and exquisite frescoed interiors.`
  },
  { 
    username: "maria", 
    description: `Mount Etna - Mount Etna is Europe’s highest and most active volcano, located on the eastern coast of Sicily. It is one of the most studied volcanoes in the world due to its frequent eruptions and its impact on the surrounding environment. Etna is a significant geological and cultural site, with ancient lava flows, craters, and rich biodiversity. It is also a popular destination for skiing in winter and hiking throughout the year.`
  },
  { 
    username: "maria", 
    description: `Costa dei Trabocchi - Among the most beautiful trabocchi are those of Punta Penna. Leave the state road and head towards the port, not forgetting to make a stop at the Punta Aderci Nature Reserve, with its sandy beach and promontory. Once again on the S.S.16, immediately after Casalbordino, you arrive at the coast of Torino di Sangro, famous for the Punta Le Morge overflow, easily reached from the beach. The journey continues from Fossacesia Marina to San Vito Marina, along a rugged coastline characterised by bays, coves and beaches. In Fossacesia, you can visit the Pesce Palombo trabocco and Punta Rocciosa. In Rocca San Giovanni, on the other hand, there are the Punta Cavalluccio, Punta Tufano, Punta Isolata, Sasso della Cajana and Punta Punciosa trabocchi`
  },
  { 
    username: "maria", 
    description: `Porticoes of Bologna - Bologna is famous for its medieval porticoes—an extensive network of covered walkways that line the streets of the city, providing shelter from the elements. These arcades stretch over 38 kilometers, making them one of the longest covered walkways in the world. The porticoes not only add to the city’s historic charm but also provide functional spaces, offering shelter and fostering a unique pedestrian-friendly environment.`
  },
  { 
    username: "maria", 
    description: `Piazza del Duomo, Pisa - The Piazza del Duomo, also known as the Field of Miracles, is home to Pisa's most famous landmark, the Leaning Tower of Pisa. This stunning ensemble of architectural masterpieces includes the cathedral, the baptistery, and the Camposanto Monumentale, all of which are exquisite examples of Romanesque and Gothic architecture. The site’s beauty and historical significance make it one of Italy’s most visited tourist destinations.`
  },
  { 
    username: "maria", 
    description: `Historic Centre of Siena - Siena is a medieval city in Tuscany that preserves its historical charm, with narrow streets, ancient buildings, and stunning public squares. The city is best known for the Palio, a centuries-old horse race held in the main square, Piazza del Campo. Siena is also famous for its Gothic architecture, especially the Siena Cathedral (Duomo), which boasts a magnificent interior and beautiful sculptures by renowned artists.`
  },
  { 
    username: "maria", 
    description: `Historic Centre of San Gimignano - San Gimignano is a small medieval town in Tuscany, famous for its well-preserved towers that define its skyline. The town has been nicknamed "The Manhattan of the Middle Ages" due to the 14 towers, which were built by wealthy families in the 12th and 13th centuries. In addition to the towers, the historic center is full of medieval buildings, palaces, and churches, making it a stunning example of medieval urban planning.`
  },
  { 
    username: "maria", 
    description: `Historic Centre of Pienza - Pienza is a small town in Tuscany that embodies Renaissance humanist urban planning. Commissioned by Pope Pius II, Pienza was transformed from a medieval village into a Renaissance gem by architect Bernardo Rossellino. The town's layout is based on the principles of ideal city design, with wide, scenic streets, charming piazzas, and elegant buildings such as the Palazzo Piccolomini. The town is also famous for its Pecorino cheese, which is produced locally.`
  },
  

  // POIs for user3
  { username: "roberto", description: `Villa Adriana (Tivoli) - Constructed in the 2nd century AD as a retreat for Emperor Hadrian, Villa Adriana is an expansive complex that spans over 120 hectares, surpassing the size of Pompeii. The villa comprises more than 30 monumental structures, including palaces, baths, libraries, theaters, and extensive gardens adorned with fountains and sculptures. Hadrian's design reflects a synthesis of architectural elements from classical antiquity and Hellenistic traditions, showcasing his appreciation for diverse cultures.` },
  { username: "roberto", description: `Villa d’Este, Tivoli - Established in the 16th century by Cardinal Ippolito II d'Este, Villa d’Este is renowned for its exquisite Renaissance gardens. The estate features an elaborate system of 51 fountains, 398 spouts, 364 water jets, 64 waterfalls, and 220 basins, all operating solely through gravity without the use of pumps. Notable fountains include the Hundred Fountains and the Fountain of the Organ, exemplifying the era's advanced hydraulic engineering and artistic design.` },
  { username: "roberto", description: `Castel del Monte - Built in the 13th century by Emperor Frederick II near Bari, Castel del Monte is distinguished by its unique octagonal shape and the harmonious blend of architectural elements from classical antiquity, the Islamic Orient, and northern European Gothic styles. Each of the castle's eight corners features an octagonal tower, and the structure's precise geometric design reflects Frederick's interest in mathematics and astronomy. The castle's purpose remains a subject of intrigue, adding to its enigmatic allure.` },
  { username: "roberto", description: `The Trulli of Alberobello - Located in the Puglia region, the Trulli are traditional limestone dwellings characterized by their conical roofs, constructed without mortar using a dry-stone technique. This architectural style dates back to the 17th century and is unique to the Itria Valley. The town of Alberobello boasts the highest concentration of these structures, which have been designated as a UNESCO World Heritage Site for their cultural significance and distinctive construction.` },
  { username: "roberto", description: `National Park of Abruzzo, Lazio and Molise - Established in 1923, this park is one of Italy's oldest and is renowned for its rich biodiversity. It serves as a sanctuary for the critically endangered Marsican brown bear, with an estimated population of about 40 individuals. The park's diverse habitats also support species such as the Apennine wolf, Abruzzo chamois, and a variety of bird species, making it a vital area for wildlife conservation and ecotourism.` },
  { username: "roberto", description: `Rocca Calascio - Perched at an elevation of approximately 1,460 meters (4,790 feet), Rocca Calascio is one of the highest fortresses in the Apennines. Constructed in the 10th century, the fortress was primarily intended for military purposes and offers commanding panoramic views of the surrounding mountains and valleys. Its strategic location and well-preserved ruins make it a significant historical and architectural landmark.` },
  { username: "roberto", description: `Santo Stefano di Sessanio - This fortified medieval village is situated at 1,250 meters above sea level within the Gran Sasso and Monti della Laga National Park. Known for its well-preserved architecture, the village has undergone extensive restoration efforts to maintain its historical integrity. Narrow stone streets, ancient buildings, and surrounding natural beauty contribute to its charm, attracting visitors interested in history and cultural heritage.` },
  { username: "roberto", description: `Sulmona - Nestled in the heart of Abruzzo, Sulmona is celebrated as the birthplace of the Roman poet Ovid and for its production of "confetti," the traditional sugared almonds associated with Italian celebrations. The town's historic center features medieval and Renaissance architecture, vibrant piazzas, and hosts annual jousting festivals that reenact medieval tournaments, reflecting its rich cultural traditions.` },
  { username: "roberto", description: `Scanno - This picturesque medieval village is renowned for its stone houses, winding alleys, and proximity to Lake Scanno, a heart-shaped lake nestled among the mountains. The lake's unique shape and the village's charming atmosphere make it a favored destination for photographers and nature enthusiasts seeking scenic beauty and tranquility.` },
  { username: "roberto", description: `Chieti - An ancient city with roots tracing back to pre-Roman times, Chieti is home to the National Archaeological Museum of Abruzzo, housed in the neoclassical Villa Frigerj. The museum's extensive collection includes artifacts from the region's early inhabitants, such as the Vestini and Marrucini tribes, and features notable exhibits like the Warrior of Capestrano, providing insights into the area's rich historical and cultural heritag.` },

  // POIs for user4
  { username: "javed1", description: `Cathedral Square to Piazza di fiera – Your route has to start from the central Piazza del Duomo, where some of Trento's architectural gems are on display, starting with the Cathedral, dedicated to Saint Vigilius, the city's patron saint. Here you can visit the famous Chapel of the Crucifix, seat of the 16th-century Council of Trento. The enchanted setting, especially in winter, with the snow, is completed by the historical Renaissance backdrop of Palazzo Cazuffi and Palazzo Rella, ancient noble residences with their façades embellished by traditional frescoed decorations; Palazzo Pretorio, the Civic Tower and the Neptune Fountain, located in the centre of the square and surmounted by a statue of the god of the sea holding a trident. A reference, it seems, to the city's ancient name (Tridentum).` },
  { username: "javed1", description: `Lanciano -Lanciano is famed for the Eucharistic Miracle of Lanciano, dating back to the 8th century. According to tradition, a monk experiencing doubts witnessed the transformation of bread and wine into flesh and blood during Mass. These relics are preserved in the Church of San Francesco. The town also boasts a well-preserved medieval district with narrow streets and historic architecture.` },
  { username: "javed1", description: `Ortona - Ortona, a coastal town, is home to the Cathedral of San Tommaso Apostolo, which houses the relics of Saint Thomas the Apostle. The cathedral, originally built over a pagan temple, was reconstructed after World War II due to significant damage. Ortona also played a pivotal role during WWII, notably in the Battle of Ortona, leading to its nickname "Western Stalingrad".` },
  { username: "javed1", description: `Pescocostanzo - This charming town is celebrated for its well-preserved Renaissance and Baroque architecture. Pescocostanzo is also renowned for traditional crafts, particularly lace-making, with the Tombolo Lace School and Museum showcasing intricate lacework. The town's historic center features stone buildings and narrow streets reflecting its rich artisanal heritage.` },
  { username: "javed1", description: `L’Aquila - As the capital of Abruzzo, L’Aquila boasts a rich medieval heritage. The city is encircled by 5.5 km of medieval walls and features numerous historic buildings and churches. Following the devastating 2009 earthquake, extensive restoration efforts have been underway to preserve and restore its architectural treasures.` },
  { username: "javed1", description: `Celano - Dominated by the imposing Piccolomini Castle, constructed in the late 14th century, Celano overlooks the Fucino plain. The castle houses art and archaeological exhibits. Nearby, the Gorges of Celano offer a scenic 5 km trek through narrow canyons, attracting nature enthusiasts and hikers.` },
  { username: "javed1", description: `Civitella del Tronto -This town is home to one of Europe's largest fortresses, the Fortezza di Civitella del Tronto, spanning over 25,000 square meters. Perched atop a rocky cliff at 600 meters above sea level, the fortress played a significant role in military history, serving as a strategic defensive structure .` },
  { username: "javed1", description: `Guardiagrele - Known as the "stone city," Guardiagrele is famed for its Gothic Church of Santa Maria Maggiore and its tradition of metalwork artisanship, particularly in wrought iron and goldsmithing. The town offers stunning views of the Maiella mountain range and is recognized for its cultural and artistic heritage.` },
  { username: "javed1", description: `Bominaco - Bominaco hosts the Oratory of San Pellegrino, often referred to as the "Sistine Chapel of Abruzzo" due to its extensive and well-preserved 13th-century frescoes depicting biblical scenes. Adjacent to it is the Church of Santa Maria Assunta, showcasing Romanesque architecture.` },
  { username: "javed1", description: `Castelli - Celebrated for its traditional maiolica pottery, Castelli has been a center of ceramic production since the Renaissance. The town is home to the Church of San Donato, whose ceiling is adorned with 780 hand-painted ceramic tiles, earning it the nickname "Sistine Chapel of Maiolica".` },

  // POIs for user5
  { username: "monica1", description: `Penne - A historic hill town in Abruzzo, Penne is known for its well-preserved medieval center with narrow alleys, Romanesque churches, and Renaissance-era palaces. It sits between the Adriatic coast and the Gran Sasso mountains, serving as a gateway to the Gran Sasso and Monti della Laga National Park. Nearby, the Lake Penne Nature Reserve offers opportunities for birdwatching, hiking, and nature tourism.` },
  { username: "monica1", description: `Teramo - Teramo combines ancient Roman ruins with elegant Renaissance and Baroque architecture. The city features a Roman amphitheater and theater, a 12th-century cathedral with Gothic and Romanesque elements, and a vibrant old town filled with cafes and boutiques. Its mix of archaeological heritage and cultural vitality makes it a unique destination in northern Abruzzo..` },
  { username: "monica1", description: `Giulianova - Giulianova is a coastal town with two distinct areas: a modern seaside resort with sandy beaches and a charming old town on the hill. The Sanctuary of the Madonna dello Splendore, surrounded by gardens and fountains, is a key religious site offering sea views and housing a museum of sacred art. Giulianova blends seaside relaxation with spiritual and historical depth..` },
  { username: "monica1", description: `Vasto - Overlooking the Adriatic Sea from a scenic cliff, Vasto features a historic center rich with medieval and Renaissance architecture, including the Caldoresco Castle and the Cathedral of San Giuseppe. The town offers access to some of Abruzzo’s best beaches and natural sites like Punta Aderci, a coastal reserve with dunes, cliffs, and marine life..` },
  { username: "monica1", description: `Pietracamela - Nestled on the slopes of the Gran Sasso mountains, Pietracamela is a picturesque mountain village known for its stone houses, narrow lanes, and alpine traditions. It’s a popular base for hikers and climbers heading toward Corno Grande and Corno Piccolo. The village is part of the Gran Sasso and Monti della Laga National Park and is listed among Italy’s most beautiful villages..` },
  { username: "monica1", description: `Navelli - Navelli is a peaceful medieval village set on a plateau, famous for producing high-quality saffron known as “red gold.” The village’s historic stone buildings, cobbled streets, and surrounding fields of crocus flowers offer a glimpse into rural Abruzzese life. Every fall, Navelli hosts a saffron festival celebrating its centuries-old agricultural heritage..` },
  { username: "monica1", description: `Abruzzo - The history of Abruzzo is long and fascinating, especially that concerning its origins. The most widely accepted hypothesis is that Abruzzo derives from Aprutium, a popular evolution of (ad)Praetutium, the land of the Pretuzi, an ancient Italic population that lived in what is now Teramo.Populated since prehistoric times, the region was home to groups of shepherds, all belonging to the Samnite lineage, who exploited the natural roads created in the long valleys for the transhumance of sheep: they travelled along mountain roads and gorges from the areas around L'Aquila to Foggia and back. Transhumance was the territory's main means of economic support.Among the populations that marked the territory were the Marsi, the Peligni, the Vestini, and the Equi, who lived in walled cities with large sanctuaries. On the subject of the Vestini, and the Samnite wars, we still have a precious testimony today: the statue of the Capestrano Warrior, a soft limestone sculpture depicting one of their warriors. It is one of the most monumental and significant works of Italic art now preserved in Chieti. ` },
  { username: "monica1", description: `Pescasseroli - Pescasseroli è adagiata in una conca all'ingresso dell'Alta Valle del Sangro a m. 1167 sul livello del mare. Questo altopiano ricco di pascoli è circondato da boschi centenari e montagne suggestive. Pescasseroli è un paese in cui è evidente la simbiosi tra natura ed architettura: il centro abitato è in perfetta armonia con le meraviglie naturali che lo circondano. Il nucleo urbano, in posizione pianeggiante, si è sviluppato attorno all'antica abbazia ed è caratterizzato da tradizionali costruzioni in muratura di pietrame e malta, adornate dalle particolari finestre con imbotti in pietra da taglio locale, denominata "pietra gentile" dal nome dell'omonima montagna. La piazza S.Antonio, così chiamata per la presenza di una chiesa oggi scomparsa, è il fulcro della vita di Pescasseroli: è colorata dai faggi e profumata dai piccoli fiori dei tigli ed è ornata, oltre che dalla sede del Comune, da una graziosa fontana, sormontata da una statuetta dell'Immacolata.
    Curiosità:
    Il nome Pescasseroli sembra derivare da "Pesculum Serulae", cioè roccia sorgente a picco (dal tardo latino "pensulum"), o masso che serra; secondo Benedetto Croce, "Pesculum ad Sorolum", cioè masso presso il piccolo Sangro (le sorgenti). La parte più antica dell'abitato sorge ai piedi dello sperone roccioso «pesco», su cui si trovano i resti di «Castel Mancino». Nella leggenda marsicana il poeta pastore Cesidio Gentile fa derivare la fondazione di Pescasseroli dalla vicenda drammatica di un giovane cavaliere crociato, Serolo, figlio del Conte Maracino, signore del castello. Serolo, partecipando alla I Crociata, incontra in Palestina la bella saracena Pesca, della quale si innamora e che sposa. In compagnia di un santo anacoreta, che aveva con sè la statuina lignea della Madonna nera, Pesca viene mandata da Serolo al castello. Una volta al castello, il vecchio Conte si invaghisce, non ricambiato, di Pesca che, fuggendogli, viene raggiunta ed uccisa in prossimità di una sorgente (quel posto è da allora chiamato «malafede»). Tornato dalla Crociata ed appresa la morte cruenta della sua sposa, Serolo muore di dolore. Sulla tomba dei due giovani sposi il vecchio Conte, in espiazione del delitto, fonda il paese che chiama Pescasseroli dall'unione dei due nomi.
    Manifestazioni:
    Festa dei SS. Pietro e Paolo (29-30/6); festa della Madonna dei Carmelo (15-16/7); Madonna di Monte Tranquillo (ultima domenica di luglio); festa della Madonna Incoronata (8-9/9).Usi e costumi:E' un'antica usanza tostare e aromatizzare i ceci con la sabbia prima delle nozze. Il costume tradizionale femminile di Pescasseroli, di istituzione relativamente recente, è tutto in nero, mentre quello antico era sfarzoso e vivace. Il costume nero fu introdotto nell'uso per una circostanza del tutto fortuita: si racconta che nel 1846 alcune donne di Pescasseroli che si recavano ad Ischia per delle cure termali furono oggetto, a Napoli, di curiosa e indiscreta attenzione. Le donne trovarono rifugio a Procida ove scambiarono i loro costumi con quelli delle donne locali.Tornate a Pescasseroli i nuovi costumi piacquero tanto da essere adottati da tutte le donne.
  astronomia:
    Agnello al cotturo, patate maritate, dolce fritto natalizio, detto 'trcnell', "la P'plla" (tipico dolce Pasquale).` },
  { username: "monica1", description: `Gran Sasso and Monti della Laga National Park– A large territory, with peaks that touch the sky and rich vegetation to protect ancient villages, hermitages and castles, among centuries-old chestnut trees and boundless seasonal blooms.Covering an area that includes three regions, Abruzzo, Lazio and Le Marche, the Park is a very complex area, divided into two distinct biogeographical regions: "Euro-Siberian" and "Mediterranean". The morphological diversity of the mountains and the high altitudes they reach make this protected area a treasure of exceptional biological richness. From the remains of the glaciers at high altitudes, to the vastness of the plains of Campo Imperatore at the foot of Corno Grande, as far as the almond trees, vineyards and olive groves further down the valley, the scenery offered by the Park goes on forever. Silent, except when flowing over jumps and waterfalls, the Tirino (the river with some of the clearest water in Europe!) is another central element of the Park: the local flora and fauna draw all the energy they need to flourish along its banks. In addition to the Tirino, several rivers and streams run through the park, bringing their energy and vitality.` },
  { username: "monica1", description: ` Campotosto Lake Nature Reserve– The largest artificial lake in Abruzzo Created in 1984 and spanning an area of 1,600 hectares, the Campotosto Lake Nature Reserve is a protected area in the province of L’Aquila. The area boasts the largest artificial lake in the region and falls within the Gran Sasso and Monti della Laga National Park.  
The reserve is an important migratory site for many animal species, some of which are endangered. The lake shore is home to the grey heron, the common shelduck, the common snipe, the great snipe—the star of the protected area—and Abruzzo’s largest colonies of common pochard and wigeon. Trout and tench are the most common fish species. The lake is very popular in the summer season among jogging and trekking enthusiasts, as well as for sport fishing, canoeing and windsurfing, while in winter it is not uncommon to find it partially or completely frozen over. The almost flat lakefront, 40 kilometres long, is a popular destination for cycling and mountain biking. Around the reserve, sport enthusiasts can find the Capannelle pass, the go-to place for motorcyclists, and the ski resorts of Campo Imperatore and Prati di Tivo. The lake is also connected to the tourist itineraries of the Horse Riding Trail of Gran Sasso and the Park’s main road.` },

  // POIs for user6
  { username: "MariaGiovanna", description: `Opi – Situato in uno splendido anfiteatro naturale, circondato da rigogliose montagne ricche di boschi, Opi conserva ancora oggi le caratteristiche di antico borgo medioevale, singolare per la posizione e l'aspetto di grande interesse archeologico. La presenza umana nel territorio di Opi ha origini remote, ne sono testimonianza i resti di un centro fortificato nel luogo in cui sorge l'attuale abitato, i tanti reperti archeologici rinvenuti nella Necropoli di Val Fondillo e i resti di un probabile tempio nelle località "Casali" e "Fonte delle Lecina".
Curiosità:
Il giorno di Sant'Antonio Abate si rinnova lo scambio dei 'cicciotti', un miscuglio di grano, fave secche, ceci e mais lessati.
Manifestazioni:
Il 24-25 giugno si festeggiano San Giovanni Battista e San Vincenzo Ferreri, patroni e protettori di Opi. La seconda domenica di settembre si festeggiano S.Emidio e la Madonna delle Grazie, mentre la prima domenica di ottobre S.Teresa e la Madonna del Rosario. La notte di Natale, dopo la santa messa, ci si ritrova in piazza della chiesa dove viene acceso un grande falò, detto "i catozze", in onore di Gesù Bambino. Il 17 gennaio si festeggia S.Antonio, giorno in cui i contadini usano far crociare i propri animali.
In agosto si svolge la Sagra degli gnocchi, una grande festa realizzata grazie alla partecipazione di molti turisti che affollano i tavoli, appositamente allestiti dalla Pro Loco per gustare gli gnocchi accuratamente preparati dalle massaie del paese.
Usi e costumi:
'Catozze', fuoco acceso la notte di Natale.
Gastronomia:
"m'paniccia", pecora al cotturo, "m'cisca" carne di pecora essiccata, frittelle di cavolfiore; cicatelli con le foglie; ricotta e pecorino. Dolci: tanozzi, torroncini, sanguinacci con riso, cicirchiata.` },
  { username: "MariaGiovanna", description: `Civitella Alfedena –Il turista che visita Civitella per la prima volta resta subito affascinato dalle forme graziose ed armoniose dell'architettura, che lascia intravedere ancora case in pietra e vicoli strettissimi in cui "perdersi" durante una passeggiata all'insegna della tradizione.
Sorge alle pendici del Monte Sterpi d'Alto, che rappresenta solo l'inizio di quel meraviglioso spettacolo che si apre subito alle spalle del grazioso borgo: l'anfiteatro della Camosciara (Zona di Riserva Integrale del Parco). Ai piedi del paesino, il Lago di Barrea, facilmente raggiungibile con una passeggiata pedonale che attraversando la Pineta porta al Ponte Vecchio e quindi sulle sponde del lago.

Curiosità:
Botteghe di artigianato. Fiaccolata di fine anno (30 dicembre) dal Monte Mava;
Presepe di carta pesta.

Manifestazioni:
Festa di Santa Lucia (seconda domenica di luglio); feste di San Nicola e Madonna del Carmine; sagra della "scrupella" (dolce fritto).

Usi e costumi: Artigianato tipico con tessitura a mano, pittura su ceramica, produzione di miele.

Gastronomia: Zuppe locali e dolci di mandorle. ` },
  { username: "MariaGiovanna", description: `InfoPoint del Parco Nazionale d'Abruzzo, Lazio e Molise – Visitor Support Hubs The InfoPoint facilities of the National Park serve as essential visitor support hubs, offering information on trails, wildlife, park regulations, and cultural attractions. Many are equipped with exhibits, educational materials, and maps, helping visitors plan their activities while promoting responsible tourism and conservation awareness.` },
  { username: "MariaGiovanna", description: ` InfoPoint Pro Loco Opi– La Pro Loco Opi – APS è stata costituita nella Primavera del 1976, iscritta all'Albo Regionale delle Pro Loco con DPGR al n.25 del 9 febbraio del 1977, fa parte dell'Unione Nazionale Pro Loco d'Italia (UNPLI).
È un'Associazione di interesse pubblico, apartitica, senza fini di lucro, volta alla promozione e alla tutela del territorio a 360°; ritiene infatti fondamentale, offrire al turista, un'immagine di Opi intesa come unicum assoluto, in cui ogni giorno armonicamente si fondono i vari aspetti turistico, culturale, naturalistico, storico, sociale ed eno-gastronomico.
La mission della Pro Loco di Opi – APS è riuscire a coniugare la tutela e la salvaguardia delle specialità locali con la vocazione allo sviluppo della crescita sociale ed al miglioramento del benessere.
I valori ispiranti dell'agire dalla Pro Loco Opi – APS sono il volontario, la collaborazione, la creazione di valore per la comunità, l'essere “luogo” di relazioni umane e sociali, tutto “a favore del territorio”, in collaborazione e in sinergia con altri enti e organizzazioni.
Per il conseguimento delle proprie finalità la Pro Loco di Opi – APS:
Promuove la cultura dell'accoglienza e dell'informazione turistica curando l'Ufficio Turistico, aperto durante tutto l'anno.
Contribuisce al miglioramento della qualità della vita del Comune, sia per i cittadini, sia per i turisti; offre appoggio logistico ad altre Associazioni e a tutti i cittadini di Opi, mettendo a disposizione fotoriproduttori, pc con stampante, servizio telefax, collegamento Wi-Fi con postazioni internet point.
Sviluppa attività di carattere sociale: è affidataria della biblioteca comunale, ricca di libri sulla flora e sulla fauna del Parco d'Abruzzo e sui tesori architettonici, gestisce il museo “C'era una volta..I Mestieri”, “C'era una volta..Trasuta e Sposa” e il Museo dello Sci.
Promuove eventi culturali, organizza convegni, corsi didattici, concerti, visite guidate e manifestazioni.` },
  { username: "MariaGiovanna", description: `InfoPoint Territoriali – In addition to the main park centers, several local InfoPoints operate across the territory, providing community-level guidance on local attractions, hiking trails, accommodation, and cultural events. These services help deepen the visitor's connection to each town while supporting local economies.` },
  { username: "MariaGiovanna", description: `Area Faunistica del Lupo – L'area Faunistica del Lupo appenninico è un'aea naturale, recintata e adiacente al paese, istituita per scopi scientifici (ripopolamento e studio) dal Parco Nazionale d'Abruzzo, Lazio e Molise; essa offre la possibilità di avvistare lupi e linci in semilibertà. L'itinerario di visita, molto semplice, porta ad osservare alcuni lupi in semi libertà, il Lago di Barrea, una grande quercia e un bosco di conifere con presenza di pino nero. Presso il Museo del lupo è possibile acquistare il pieghevole illustrativo di questo facile sentiero natura. Il percorso natura parte accanto al Museo del Lupo, sulla via con i selci neri, che sale al piazzale Santa Lucia. La strada si affaccia sulla destra, sull'area faunistica del Lupo appenninico, in un pannello illustrativo sono riportate delle notizie su questo magnifico predatore.
     Con un po' di attenzione e facile scorgere alcuni esemplari di questo animale sopra la collina che domina la riserva. Raggiunta la sommità, si ha un bel panorama sul Lago di Barrea, il piazzale offre invece, una veduta classica del borgo di Civitella Alfedena. Su di un lato della grande piazza, c'è il “capannino” del Parco, composto di pannelli illustrativi sui sentieri escursionistici dell'area protetta. Al centro, accanto alla piccola fontana, vi è una grande pianta di tiglio, che fiorisce in primavera. Fino a pochi anni or sono, le donne del paese vi si recavano a raccogliere i fascetti odorosi per farne delle tisane. Poco più in la, una grande guercia secolare (cerro) è invece posta davanti alla chiesa di S. Lucia. La chiesa anche se da poco rifatta, conserva una struttura a croce greca, che la lega all'antica storia religiosa dei maroniti che vi giunsero dal lontano Libano. Due monaci maroniti del VIII sec., Barnam e Josaphat, raffigurati in due statue di legno, opera di scalpellini napoletani,  sono poste  dentro la chiesa, accanto alla statua cinquecentesca di S. Lucia. Sul lato del piccolo campanile, un'apertura porta sul viottolo che cala attraverso il bosco di conifere (alberi di pino nero e abete rosso), piantati all'inizio del 1900 dai bambini di Civitella su iniziativa di un maestro elementare). Poco dopo, lasciando la discesa,  si prosegue a destra per arrivare dietro la chiesa, dove si trova un'area attrezzata per il pic nic. Salendo la piccola dorsale del colle con rose selvatiche, prugnoli e maggiociondoli, si giunge alla palina N. 9. Si riprende poi il sentiero che poco più avanti scende sulla destra, superate alcune rocce di natura calcarea, colonizzate da muschi e licheni, alla fine del bosco si raggiunge nuovamente la stradina selciata. Voltando a destra in salita e costeggiando sulla sinistra l'area recintata del Lupo, si torna al punto di partenza.` },
  { username: "MariaGiovanna", description: `Area Faunistica del Cervo – Situata a 1500 m. di quota, nei pressi del Centro Informazioni di Gamberale, l'area faunistica è stata realizzata su terreni di proprietà del Comune di Gamberale (CH) siti nel Comune di Ateleta (AQ), in località Laghetto S. Antonio. L'area faunistica del cervo nasce nel 2003 con animali provenienti da altre aree faunistiche e centri di recupero; la notevole estensione dell'area, oltre 10 ettari e la presenza di vaste porzioni di aree di bosco, cespuglieti e pascoli, oltre che corsi d'acqua naturali, contribuisce a rendere le condizioni di vita degli animali ospitati molto vicine a quelle dei cervi a vita libera presenti in diversi settori del Parco.
Gli animali sono facilmente avvistabili e da metà settembre a fine ottobre, è possibile ascoltare le vocalizzazioni, i cosiddetti bramiti, che i maschi adulti di cervo emettono nel periodo riproduttivo. Attualmente l'area ospita sedici esemplari di cervo.
Come tutte le aree faunistiche del Parco, anche l'area faunistica del cervo costituisce un notevole elemento di sensibilizzazione nei confronti dei turisti, delle scolaresche e della popolazione residente.
Nei pressi dell'area, all'interno del bosco di faggio, è presente un percorso ad anello accessibile ai diversamente abili di particolare valenza naturalistica.` },
  { username: "MariaGiovanna", description: `Area Faunistica dell’Orso – L'Area Faunistica dell'Orso è stata inaugurata il 18 settembre 2010 e si trova a Campoli Appennino (FR), paese del Parco Nazionale d'Abruzzo Lazio e Molise (PNALM) a circa 7 km da Sora.

Il paese di Campoli, nella conformazione attuale, ha origine medioevale (come testimoniano la Torre ed i resti delle mura di fortificazione), sorge a 650 m s.l.m., conta una popolazione di circa 1700 abitanti ed ha la particolarità di svilupparsi interamente intorno a un'estesa dolina - localmente chiamata "Fossa" o "Tomolo" - manifestazione del fenomeno carsico particolarmente diffuso nell'Appennino centrale. Nella sua forma sub-ellittica, si estende per 630×400 m, ed ha una profondità di 130 m, con la caratteristica di avere i versanti esposti a Nord e Sud di differente età geologica.

Questo piccolo borgo dell'Appennino laziale-abruzzese - già conosciuto per il suo celebre e raffinato tartufo, apprezzato a livello nazionale e internazionale - grazie all'istituzione dell'Area Faunistica si è meritato l'appellativo di "Città dell'Orso e del Tartufo" come recita un pannello di accoglienza posto all'entrata del paese.

Il territorio comunale campolese per buona parte si trova nella cosiddetta zona di protezione esterna del Parco Nazionale d'Abruzzo Lazio e Molise. Una porzione della sua superficie, anche se di minore estensione, rientra entro i confini veri propri del Parco: è perciò possibile ammirarne tutt'intorno il magnifico paesaggio, fatto di vette mozzafiato ed estesi boschi.

La ricchezza naturalistica di Campoli - praticamente incontaminata - lo ha reso da sempre un luogo privilegiato per poter osservare la fauna tipica del Parco che spesso si spinge fino ai limiti del centro abitato. L'orso, che ne è l'elemento più rappresentativo, non fa eccezione e in qualche caso non disdegna delle inaspettate visite a "domicilio" ai paesani.` },
  { username: "MariaGiovanna", description: `Centro Visita dell’Orso – Nel cuore del Parco nazionale D'Abruzzo Lazio e Molise, nello splendido borgo di Villavallelonga a 1005 metri d'altezza, sorge il Centro Visita dell'Orso di Villavallelonga. Struttura del Parco, il Centro visite nasce con finalità educativa ed informativa incentrata sulla figura del plantigrado simbolo del Parco, l'Orso Bruno Marsicano.
Museo dell'Orso - Il percorso museale illustra la vita di questo famoso plantigrado attraverso pannelli, bacheche e diorami; periodicamente vengono ospitate mostre temporanee. Ai piccoli visitatori è dedicato un punto di interpretazione della natura e nella sala proiezioni annessa è possibile assistere a filmati naturalistici generali o specifici sulla vita e le abitudini dell'Orso.
Postazione 3D - attraverso un video naturalistico in 3D il visitatore conosce da vicino la fauna del Parco, in compagnia dell'orso, del lupo e dei tanti animali che abitano il territorio.
Ufficio Informazioni - Situato all'ingresso del museo, personale specializzato nel servizio di front office fornisce indicazioni e assistenza per la partecipazione alle attività di educazione ed animazione ambientale, sul programma di escursioni e sulle modalità d'iscrizione alle varie attività.
Area Faunistica e Sentiero Natura - Percorrendo il Sentiero Natura attrezzato si scorge l'ampia area recintata che ospita in stato di semilibertà un esemplare di Orso Bruno Marsicano.
Area shop ed esposizione prodotti locali - nella struttura è presente un'area shop per l'acquisto di souvenirs e materiale didattico e scientifico sul Parco nazionale d'Abruzzo, Lazio e Molise. Per chi vuole conoscere il territorio attraverso l'artigianato e l'enogastronomia locale è allestito inoltre uno spazio di esposizione di prodotti tipici locali artigianali ed enogastronomici.
Area pic-nic - Nell'area adiacente il Museo sono inoltre presenti 3 aree picnic all'aperto.` },
  { username: "MariaGiovanna", description: `Sala dei Pipistrelli – Located in Barrea, this exhibit space is dedicated to the study and appreciation of bats. Visitors can explore displays with photos, books, and videos, and even watch a live stream of a nearby bat colony. It’s a unique way to educate the public about the ecological importance of bats and challenge common myths.` },

  // POIs for user7
  { username: "javed", description: `Percorso Espositivo sull’Orso – This educational exhibit is dedicated to the natural history of the Marsican brown bear and its relationship with humans. It offers insights into the bear's biology, behavior, and the cultural significance it holds in the region. Through interactive displays and informative panels, visitors can learn about conservation efforts and the importance of coexistence between bears and local communities.` },
  { username: "javed", description: `Museo della Transumanza – The Museum of Transhumance, located within the Caseificio Di Nucci, offers a unique experience combining history, emotion, and taste. It showcases wooden tools, ancient books, and modern artworks that narrate the story of a family dedicated to cheese-making for centuries. Visitors can engage in educational activities, guided tastings of local products, and explore the rich pastoral heritage of the region.` },
  { username: "javed", description: `Museo Civico Archeologico A. De Nino – Il Museo Civico Archeologico A. De Nino conserva preziosi reperti provenienti dalle numerose tombe scavate nelle diverse aree della Necropoli di Campo Consolino: collari di bronzo, anelli digitali, perle di pasta vitrea, collane in ambra, pendagli in bronzo e le cosiddette châtelaine dalle tombe femminili; dalle sepolture maschili invece armi in ferro e bronzo, cinturoni, dischi corazza con inciso il cosiddetto "quadrupede fantastico a collo di cigno" ed una delle più belle spade che la storia ci abbia restituito.

Il percorso museale si snoda in un'unica sala, nella quale sono collocati i reperti più importanti della collezione alfedenese, inclusa una parte di quelli trafugati dall'esercito tedesco, restituiti ad Alfedena nel 1974 dall' Università di Tubinga a cui erano stati affidati dopo la guerra da un ex ufficiale della Wehrmacht, organizzati in teche secondo la loro catalogazione. Vi sono inoltre ricostruite due tombe così come rinvenute al momento dello scavo e la documentazione fotografica e topografica della posizione dei siti fondamentali dell'antica Aufidena. Una delle teche è dedicata all'esposizione dei diari di scavo degli archeologi De Nino e Mariani.

Il museo fu istituito e inaugurato nel 1897, quando, con i saggi di scavo per la costruzione della linea ferroviaria Sulmona - Carpinone furono scavate anche le prime tombe della necropoli dall'archeologo abruzzese Antonio De Nino, per una buona parte insieme al collega Lucio Mariani, il cui diario di scavo è tuttora visibile nella sala espositiva principale.

Ospitato in passato nelle sale al piano terra dell'attuale edificio comunale, il museo fu depredato dall'esercito tedesco nel 1943; l'edificio fu poi minato e distrutto ed il resto dei reperti, recuperato successivamente tra le macerie, fu trasferito nel Museo Archeologico nazionale d'Abruzzo a Chieti. Tra la metà degli anni '70 e la fine degli anni '80 del 900 nuove campagne di scavo hanno aperto la strada alla possibilità di realizzare il nuovo edificio museale dove esso è oggi collocato, al margine della necropoli di Campo Consolino; il nuovo museo, dedicato ad Antonio De Nino, è stato inaugurato nel 1987, novant'anni dopo il primo.

Alfedena, oggi ambita meta turistica nel cuore delle montagne del Parco Nazionale d'Abruzzo, Lazio e Molise, costituisce un caposaldo per la conoscenza delle culture arcaiche in Abruzzo, delle quali rappresenta una delle testimonianze più cospicue: una vasta necropoli a valle dell'abitato e un'ampia acropoli a circa 500 m di distanza, testimoniano oggettivamente l'esistenza di una città sannitica.` },
  { username: "javed", description: `Rolle Railz Park–The Rolle Railz Park, on the slopes of Passo Rolle, 9 kilometres from San Martino di Castrozza, can be reached from the Castellazzo chairlifts: it offers 15 km of slopes, with a free style area enclosed by nets and a snowboard school area. In San Martino di Castrozza you’ll find the San Martino SnowPark. Located between the Conca and Acandola slopes in the upper part of the Alpe Tognola. Areas of fresh snow are serviced with ski lifts: the route is 600 metres long, with an average gradient of 18-20% and some peaks reaching 48%.

For those who prefer to walk in the snow in snowshoes or cross country skiing, there is no shortage of panoramic trails. The easier trails are towards the Calaita lake and more difficult ones towards the Alpe Tognola. ` },
  { username: "javed", description: `InfoPoint CETS –These specialized InfoPoints are managed by facilities committed to the principles of the European Charter for Sustainable Tourism (CETS). They offer information on eco-friendly travel options, sustainable practices, and initiatives aimed at preserving the park's biodiversity while supporting local economies. Visitors can learn about responsible tourism and how to minimize their environmental footprint. ` },
  { username: "javed", description: `San Martino di Castrozza – San Martino di Castrozza is one of the oldest tourism locations in the Dolomites. The first hotel was opened in 1873 to allow people to enjoy the impressive scenery of the mountains and for the British and German mountaineers who first discovered them.
From the town, the view sweeps over the Palec group. This includes Cimon della Pala, the Rosetta, the Sass Maor, the peaks of Val di Roda and della Madonna, the peaks of Feltre, Monte Pavione and Colbrico.
Fiera di Primiero, its hamlet is also very pleasant. It houses one of the most interesting buildings in the valley, the historic Palazzo del Dazio. Dated from the second half of the fifteen century, in Austrian late gothic style. It was held by the magistrate of the mines, as mining was the main activity of the area for centuries. From the same era the Palazzo Scopoli, known today as the Casa del Cibo, house of food, to visit for a better understanding of the excellence of mountain gastronomy.` },
  { username: "javed", description: `Science Museum– From dinosaurs to prehistoric humans, from pristine views to the most revolutionary technologies. Inside the MUSE science museum in Trento, you can explore nature from every angle.

The Science Museum will strike you from the outside, thanks to its innovative forms that recall the shape of the Trentino mountains. The structure, opened to the public in 2013, bears the signature of the star architect Renzo Piano.

Once you enter, you will find yourself catapulted into a path where the visitor is the absolute protagonist: you can experience what you are learning firsthand, through interactive games and immersive environments. The permanent exhibition demonstrates all the facets of life on Earth, with the aim - ambitious but essential - of building a better future for the planet and its inhabitants. Not surprisingly, the same building is built respecting eco-sustainability criteria, with natural materials and using renewable energy sources.

The proposed routes are suitable for all age groups. Dedicated to the littlest visitors (0-5 years), there is the Maxi Ooh!, an exhibition and sensory space tailored to children. Do not miss the FabLab, a real "workshop of ideas", and the tropical greenhouse, where in an instant you will be transported from the landscapes of the alpine arc to the tropical ones of Tanzania.` },
  { username: "javed", description: `Cathedral Square to Piazza di fiera – Your route has to start from the central Piazza del Duomo, where some of Trento's architectural gems are on display, starting with the Cathedral, dedicated to Saint Vigilius, the city's patron saint. Here you can visit the famous Chapel of the Crucifix, seat of the 16th-century Council of Trento. The enchanted setting, especially in winter, with the snow, is completed by the historical Renaissance backdrop of Palazzo Cazuffi and Palazzo Rella, ancient noble residences with their façades embellished by traditional frescoed decorations; Palazzo Pretorio, the Civic Tower and the Neptune Fountain, located in the centre of the square and surmounted by a statue of the god of the sea holding a trident. A reference, it seems, to the city's ancient name (Tridentum).` },
  { username: "javed", description: `Eremo di San Bartolomeo in Legio – Carved into a cliff in the Majella mountains, this 11th-century hermitage offers a profound spiritual and historical experience. Accessible via a scenic hiking trail, the site features a small chapel with remnants of medieval frescoes and provides panoramic views of the surrounding valley. It stands as a testament to the region's monastic traditions and architectural ingenuity.` },
  { username: "javed", description: `Abbazia di San Giovanni in Venere – Perched atop a hill overlooking the Adriatic coast, this 12th-century Benedictine abbey seamlessly blends Romanesque and Gothic architectural styles. The complex includes a basilica adorned with intricate frescoes and a monastery surrounded by lush gardens. Its elevated position offers breathtaking views of the sea and the surrounding countryside, making it a significant religious and cultural landmark.​` },

  // POIs for user8
  { username: "elizabeth", description: `Castello Piccolomini – Celano - Perched atop a hill in Celano, Castello Piccolomini is a 15th-century fortress that dominates the Fucino plain. Initiated in 1392 and completed in 1463 by Antonio Piccolomini, nephew of Pope Pius II, the castle features a rectangular plan with four corner towers and a central courtyard. Today, it houses the National Museum of Sacred Art of the Marsica, showcasing paintings, sculptures, and sacred vestments from the 6th to the 18th century, as well as archaeological artifacts from the Torlonia Collection, discovered during the draining of Lake Fucino in the 19th century.` },
  { username: "elizabeth", description: `Museo delle Genti d'Abruzzo – Pescara -Located in the heart of Pescara's historic district, the Museo delle Genti d'Abruzzo offers an extensive journey through the cultural evolution of the Abruzzo people. Housed within the ancient Bourbon barracks, the museum's 16 exhibition halls trace human presence in the region from the Paleolithic era to contemporary times. Interactive displays and artifacts provide insights into traditional crafts, daily life, and the rich heritage of Abruzzo's inhabitants.` },
  { username: "elizabeth", description: `Abbazia di Santo Spirito al Morrone – Sulmona -ituated approximately 5 kilometers from Sulmona at the base of Monte Morrone, the Abbey of Santo Spirito al Morrone is a monumental complex with a rich history. Founded in the 13th century and later expanded, the abbey features a rectangular layout enclosed by imposing walls, with inner courtyards and a grand 18th-century church showcasing Baroque elements. Once the residence of Pope Celestine V, the abbey now serves as a cultural and historical landmark, reflecting its significance in the region's religious and architectural heritage. ` },
  { username: "elizabeth", description: `Chieti Historic Center – Chieti - As one of Italy's oldest cities, Chieti's historic center is a treasure trove of architectural and cultural landmarks. The cityscape is adorned with Roman ruins, including an amphitheater and temples, medieval churches like the Cathedral of San Giustino, and elegant Renaissance and Baroque palaces. Wandering through its narrow alleys reveals a blend of historical periods, offering a captivating experience of Chieti's rich past.` },
  { username: "elizabeth", description: `Museo Archeologico Nazionale di Campli – Campli - Housed within the former convent of San Francesco, the National Archaeological Museum of Campli offers a deep dive into the region's ancient history. The museum's collection includes artifacts from the Italic and Roman periods, with significant finds from local necropolises. Visitors can explore well-curated exhibits that provide insights into the daily lives and customs of ancient civilizations that once inhabited the area.` },
  { username: "elizabeth", description: `Civitella del Tronto Fortress – Teramo - Dominating the skyline of Civitella del Tronto, this fortress is one of the most monumental military engineering feats in Italy, stretching over 500 meters in length. Constructed in the 16th century, it served as a strategic stronghold due to its commanding position overlooking the Tronto River valley. The fortress played a pivotal role in various historical conflicts, including resisting French sieges and serving as the last Bourbon bastion during Italy's unification.` },
  { username: "elizabeth", description: `Atri Cathedral and Diocesan Museum – Atri - The 13th-century Atri Cathedral, dedicated to Santa Maria Assunta, is renowned for its stunning frescoes by the 15th-century painter Andrea de Litio. Adjacent to the cathedral, the Diocesan Museum houses a collection of religious artifacts, including liturgical objects, manuscripts, and artworks that reflect the spiritual and artistic heritage of the region. Together, they offer a profound insight into Atri's ecclesiastical history.` },
  { username: "elizabeth", description: `Castello Aragonese – Ortona - Overlooking the Adriatic Sea, Ortona's Castello Aragonese is a Renaissance fortress built in 1492 by the Aragonese to defend against Ottoman incursions. The castle's strategic coastal position offers panoramic views of the sea and surrounding landscape. Despite suffering damage during World War II, the restored structure now serves as a cultural venue and symbol of Ortona's historical resilience. ` },
  { username: "elizabeth", description: `Museo Capitolare – Atri - Established in 1912, the Museo Capitolare di Atri is one of the oldest ecclesiastical museums in Italy. Located within the former Benedictine monastery adjacent to the cathedral, the museum's ten rooms display a diverse collection of art ranging from the 13th to the 20th century. Exhibits include illuminated manuscripts, paintings, sculptures, and precious liturgical objects, reflecting the rich religious and artistic heritage of the region.` },
  { username: "elizabeth", description: `Complesso di San Clemente a Casauria – Founded in 871 AD, the Abbey of San Clemente a Casauria is a masterpiece of Romanesque-Gothic architecture. Located along the ancient Via Claudio-Valeria, the abbey boasts an impressive façade adorned with intricate sculptures and a richly decorated interior. Historically significant, it once housed the relics of Pope St. Clement and played a vital role in the religious and cultural development of the region.` },

  // POIs for user9
  { username: "rita", description: `Museo del Costume e della Tradizione della Nostra Gente – Pollutri - Located in Guardiagrele, the Museo del Costume e della Tradizione della Nostra Gente offers an insightful look into the local culture and traditions. The exhibition hall houses over 300 period objects, divided into two sections: one dedicated to family life, depicting both daily activities and significant events like births and weddings; and the other focusing on rural and artisanal community life, showcasing tools and documents that narrate the history of the patriarchal family and the peasant and artisan community. ` },
  { username: "rita", description: `Museo della Ceramica – Castelli - Situated in the heart of Italy’s ceramic tradition, the Museo delle Ceramiche in Castelli is housed in the ancient Franciscan convent dating back to the mid-16th century. The museum showcases a valuable collection of maiolica pottery, reflecting the rich history of ceramic art in the region. The building itself has served various purposes over the centuries, including functioning as a depot and hosting the first seat of the State Art Institute F.A. Grue in 1905, before becoming a museum in 1984.` },
  { username: "rita", description: `Teatro Marrucino – Chieti - Established in the early 19th century, Teatro Marrucino is a historic theater located in Chieti, Italy. Originally named Teatro San Ferdinando in honor of King Ferdinand I of the Two Sicilies, it was later renamed Teatro Marrucino in 1861, following the unification of Italy, to pay homage to the ancient Marrucini people of pre-Roman Abruzzo. The theater is renowned for its neoclassical architecture and has been a cultural hub, hosting a variety of performances including operas and concerts.` },
  { username: "rita", description: `Eremo di San Domenico – Villalago - Nestled in the Sagittario Valley along the shores of the picturesque Lake San Domenico, the Eremo di San Domenico is a tranquil hermitage with ancient origins linked to the figure of Saint Domenico. According to local tradition, the hermitage was carved out by Saint Domenico around the year 1000. The site offers a serene environment for reflection and is a testament to the region's spiritual heritage.` },
  { username: "rita", description: `Museo Naturalistico e Archeologico “Villa Badessa” – Rosciano - Villa Badessa, a fraction of Rosciano near Pescara, is unique in Abruzzo as it seeks to revive the local Arbëreshë culture, stemming from Albanian emigrants who settled in the area centuries ago. The museum explores both the natural environment and archaeological past of the region, offering insights into the diverse cultural influences that have shaped the local heritage.` },
  { username: "rita", description: `Fontevecchia – Spoltore - Associazione Fontevecchia, founded in 2011 by residents of the ancient village houses Troiano of Spoltore, is dedicated to the recovery and enhancement of central and southern Italian popular traditions. The association engages in various cultural activities aimed at preserving and promoting the rich heritage of the region.` },
  { username: "rita", description: `Museo dell'Olio di Loreto Aprutino – The Museo dell’Olio, inaugurated in 2005, is housed in a historic olive oil mill built in 1880 by Raffaele Baldini Palladini. The museum celebrates the region's centuries-old olive oil production, showcasing the evolution of olive pressing techniques and the cultural significance of olive oil in Abruzzo. ` },
  { username: "rita", description: `Museo della Civiltà Contadina – Penne - Located in the former episcopal palace adjacent to the Cathedral of San Massimo, the Museo Archeologico G.B. Leopardi in Penne preserves agricultural tools, domestic objects, and reconstructions of rural life, offering a glimpse into the region's agrarian past. The museum is managed by dedicated staff and provides educational insights into the traditional farming practices of the area.` },
  { username: "rita", description: `Palazzo Ducale – Tagliacozzo - The Palazzo Ducale in Tagliacozzo is an important historical building dating back to the 14th century. Originally built by the Orsini family, who governed the city for centuries, the palace has undergone various modifications over the centuries, reflecting a blend of architectural styles. It stands as a testament to the town's noble past and architectural heritage.` },
  { username: "rita", description: `Eremo di San Venanzio – Raiano -Perched within the Regional Natural Reserve of the Gole di San Venanzio, the Eremo di San Venanzio is a hermitage built on a cliff overlooking a gorge. Accessible via a narrow footbridge, the hermitage is surrounded by lush vegetation and offers a serene retreat for visitors. The site is associated with Saint Venantius of Camerino and holds historical and spiritual significance.  ` },

  // POIs for user10
  { username: "usama", description: `Museo delle Arti e Tradizioni Popolari – L’Aquila - Located in the historic quarter of San Pietro di Coppito in L’Aquila, the Museo delle Arti e Tradizioni Popolari is dedicated to preserving and showcasing the rich cultural heritage of the Abruzzo region. The museum's collection includes traditional costumes, handcrafted textiles, agricultural tools, and various artifacts that illustrate the daily life and customs of the local populace through the centuries. Visitors can gain insights into the region's folklore, crafts, and traditions, making it a valuable resource for understanding Abruzzo's social history.` },
  { username: "usama", description: `Museo Archeologico – Guardiagrele - Situated in Guardiagrele, the Museo Archeologico "Filippo Ferrari" offers a glimpse into the area's ancient past. The museum houses artifacts from the late Bronze Age to the Roman period, including weapons, pottery, and ornaments discovered in the nearby necropolis of Comino. These exhibits provide valuable insights into the early civilizations that inhabited the region.` },
  { username: "usama", description: `Castello Cantelmo – Pettorano sul Gizio - Perched atop Colle della Guardiola, Castello Cantelmo dominates the landscape of Pettorano sul Gizio. Dating back to the 11th century, this medieval fortress features an irregular layout with cylindrical towers and a central keep. Originally built as a defensive stronghold, the castle offers panoramic views of the Gizio Valley and the surrounding mountains. Today, it hosts exhibitions and cultural events, allowing visitors to explore its historical significance and enjoy the scenic vistas.` },
  { username: "usama", description: `Chiesa di Santa Maria del Lago – Moscufo - The Chiesa di Santa Maria del Lago in Moscufo is a remarkable example of Romanesque architecture, believed to have been constructed in the 12th century. The church's austere brick façade is adorned with a richly sculpted portal featuring symbolic motifs. Inside, the church houses an exquisite ambon (pulpit) created by the master sculptor Nicodemo in 1159, showcasing intricate carvings and considered a masterpiece of medieval art. The interior also preserves remnants of 12th-century frescoes, adding to its historical and artistic value.` },
  { username: "usama", description: `Museo Civico – Sulmona - Housed within the Palazzo della Santissima Annunziata, Sulmona's Museo Civico offers a comprehensive overview of the region's history and art. The museum is divided into sections that include archaeological finds from the Peligna Valley, medieval artifacts, and a rich art gallery featuring works from the 13th to the 18th centuries. Notable exhibits include ancient Roman inscriptions, religious sculptures, and Renaissance paintings, providing visitors with a deep understanding of Sulmona's cultural evolution.` },
  { username: "usama", description: `Chiesa di San Pietro ad Oratorium – Located near the Tirino River, approximately six kilometers from Capestrano, the Chiesa di San Pietro ad Oratorium is a Romanesque church with origins tracing back to the 8th century. Reconstructed in the 12th century, the church features a simple façade with a notable inscription attributing its foundation to King Desiderius. Inside, the church boasts a 13th-century ciborium and well-preserved frescoes. An intriguing feature is the presence of the "Sator Square" on one of its exterior walls, a mysterious ancient Latin palindrome whose significance continues to be a subject of scholarly interest` },
  { username: "usama", description: `Museo della Lana – Scanno - The Museo della Lana in Scanno is dedicated to the town's rich history of wool production, which has been a cornerstone of its economy and culture for centuries. The museum is housed in a restored woolen mill and showcases the entire process of wool production, from shearing to weaving. Exhibits include traditional tools, machinery, and garments, offering visitors an immersive experience into the craftsmanship and traditions of Scanno's wool industry.` },
  { username: "usama", description: `Convento di San Francesco – Castelvecchio Subequo - Founded in 1288, the Chiesa e Convento di San Francesco in Castelvecchio Subequo is a significant religious complex known for its remarkable medieval architecture and art. The church features a series of frescoes depicting scenes from the life of St. Francis, attributed to the school of Giotto. The adjacent convent houses a Museum of Sacred Art, displaying precious reliquaries, liturgical objects, and artworks that reflect the spiritual and cultural heritage of the region` },
  { username: "usama", description: `Torre di Cerrano – Pineto - The Torre di Cerrano is a historic coastal watchtower located between the towns of Pineto and Silvi. Built in the 16th century as part of a defensive system against Ottoman pirates, the tower now serves as the centerpiece of the Torre del Cerrano Marine Protected Area. It houses a marine biology museum and offers educational activities related to marine conservation. The surrounding area features pristine beaches and dune ecosystems, making it a popular destination for both history enthusiasts and nature lovers` },
  { username: "usama", description: `Museo Paleontologico – Located in Lettomanoppello, the Museo Paleontologico is dedicated to the rich fossil heritage of the Majella region. The museum's collection includes fossils dating back millions of years, offering insights into the prehistoric life that once inhabited the area. Exhibits feature specimens of ancient flora and fauna, providing a comprehensive overview of the region's geological history and making it an important center for paleontological research and education.` }
];
// === 🏷️ Extract Title from Description ===
samplePOIs = samplePOIs.map(poi => {
    const titleMatch = poi.description.match(/^(.+?)\s*[-–]\s*/);
    const title = titleMatch ? titleMatch[1].trim() : poi.description.split('.')[0];
    return {
      ...poi,
      title
    };
  });
const userPOICounters = {};
samplePOIs.forEach(poi => {
  const user = poi.username;
  if (!userPOICounters[user]) userPOICounters[user] = 0;
  poi.poiIndex = userPOICounters[user];
  userPOICounters[user]++;
});

// === 4. Clear + Insert ===
(async () => {
  try {
    await POI.deleteMany({});
    console.log('🧹 Existing POIs cleared.');

    await POI.insertMany(samplePOIs);
    console.log('✅ Sample POIs inserted successfully');

    mongoose.disconnect();
  } catch (err) {
    console.error('❌ Error:', err);
    mongoose.disconnect();
  }
})();

