require('dotenv').config();
const mongoose = require('mongoose');

// === 1. Connect to MongoDB ===
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
.then(() => console.log('✅ Connected to MongoDB'))
.catch(err => console.error('❌ Connection error:', err));

// === 2. Define Schema ===
const poiSchema = new mongoose.Schema({
    username: String,
    title: String,
    description: String,
    highlightedData: [{
      entity: String,
      url: String
    }],
    poiIndex: Number
  });
  
const POI = mongoose.model('POI', poiSchema);

// === 3. Sample POIs ===
let samplePOIs = [
  // POIs for user1
  { username: "user1", description: `Camping Wolf - Il Camping Wolf è un campeggio di montagna situato a Civitella Alfedena, borgo nel cuore del Parco Nazionale d'Abruzzo, un'oasi di natura incontaminata a 2 ore di viaggio da Roma e Napoli. Il campeggio offre una vacanza all'insegna dell'immersione totale nella natura, nel silenzio, tra l'ombra delle querce: circa 60 piazzole per tende, camper e caravan/roulotte, tra muretti a secco, fiori selvatici, alberi. Il lago di Barrea si raggiunge in soli 10 minuti di breve e facile escursione a piedi dal campeggio, lungo un sentiero che segue il tracciato dell'antico tratturo che univa questi territori ai pascoli di Puglia e Lucania. Il centro storico di Civitella dista appena 300 m, con negozi di alimentari/minimarket, bar, ristoranti, farmacia, sportello ATM Bancomat, fermata mezzi di trasporto pubblici. I vicini paesi di Villetta Barrea, Barrea, Opi, Pescasseroli, Scanno sono raggiungibili con brevi gite in auto o con mezzi pubblici. Il Camping Wolf è un campeggio in cui il rispetto per la natura ci guida in ogni scelta: dalle architetture ecologiche, alla scelta dei materiali naturali (legno, pietra), agli impianti tecnologici rinnovabili (pannelli solari per l'acqua calda sanitaria, pannelli fotovoltaici per l'elettricità, coibentazione con pannelli in fibra di legno per garantire microclimi miti all'interno degli edifici, erogatori a risparmio idrico per docce, rubinetti), alla selezione di prodotti enogastronomici, biologici e fatti in casa che potete trovare presso il nostro bar/ristoro. Il campeggio è anche frequentato a volte da alcuni animali selvatici del Parco: cervi e cerbiatti, tassi, ricci, volpi, piccoli animali del bosco, ghiri, lucciole, ghiandaie, upupe, picchi, piccoli rapaci e decine di altre specie. I lupi (nostro animale totem, amato simbolo della nostra natura più intima e selvaggia) della vicinissima area faunistica a volte ululano e cantano nelle sere e nelle notti per ricordarci il dono di essere qui, in un contatto raro con i segreti del mondo naturale.` },
  { username: "user1", description: `Historic Centre of Florence - Built on the site of an Etruscan settlement and later the Roman colony of Florentia. Florence is a treasure trove of art, history, and architecture, with masterpieces by Michelangelo, Botticelli, and Leonardo da Vinci. Major attractions include the Florence Cathedral (Duomo), Uffizi Gallery, and Ponte Vecchio. Florence’s historical center is an open-air museum, showcasing the creativity and intellectual achievements of the Renaissance period.` },
  { username: "user1", description: `Rock Drawings in Valcamonica - Home to approximately 300,000 petroglyphs from the Epipaleolithic era to the Middle Ages. The rock carvings provide an exceptional insight into prehistoric life and spiritual practices in Italy. The Valcamonica rock art is one of the largest and most important collections of prehistoric art in Europe, and it has been recognized as a UNESCO World Heritage Site for its cultural significance.` },
  { username: "user1", description: `Vineyard Landscape of Piedmont - Langhe-Roero and Monferrato offer outstanding wine-growing landscapes shaped over centuries. The terraced hillsides and picturesque villages are integral to the cultivation of world-renowned wines such as Barolo and Barbaresco. The vineyard landscape not only embodies agricultural excellence but also reflects a deep connection between local culture, tradition, and the landscape itself.` },
  { username: "user1", description: `Cittadella of Alessandria - A star fort and citadel built in the 18th century, notable for its preserved fortifications. Designed as a military stronghold, the citadel played a significant role in the defense of the region. Its preserved fortifications and impressive architecture make it a valuable example of military architecture from the late Renaissance period.` },
  { username: "user1", description: `City of Vicenza and the Palladian Villas - Protects buildings designed by architect Andrea Palladio. Vicenza is a city that houses some of the most remarkable buildings designed by Palladio. His villas, with their distinctive style blending classical and Renaissance elements, are spread across the surrounding countryside of Vicenza. The city itself features several of his architectural masterpieces, including the Teatro Olimpico and Villa Rotonda.` },
  { username: "user1", description: `Historic Centre of Urbino - A major Renaissance cultural center with intact medieval walls and Ducal Palace. Urbino, a major cultural center during the Renaissance, is known for its well-preserved medieval walls and the Ducal Palace, one of Italy’s finest examples of Renaissance architecture. The city was home to the influential Duke Federico da Montefeltro, whose court attracted leading artists, scholars, and humanists.` },
  { username: "user1", description: `Historic Centre of Rome - Includes landmarks like the Colosseum, Roman Forum, and the Pantheon. Rome is home to some of the most famous landmarks in the world. The city’s historic center is a vast repository of art, architecture, and culture, marking the city as a major center of Western civilization and a religious hub as the home of the Vatican.` },
  { username: "user1", description: `Historic Centre of Naples - One of the oldest cities in Europe, with a rich mixture of Greek, Roman, and medieval heritage. Naples is home to landmarks such as the Royal Palace of Naples, Castel dell'Ovo, and the ancient Roman city of Pompeii, located just outside the city. Its history spans over 2,800 years and is marked by a unique blend of cultures and civilizations.` },
  { username: "user1", description: `Sassi and the Park of Rupestrian Churches of Matera - Known for ancient cave dwellings and rock-hewn churches. Matera is renowned for its ancient cave dwellings and rock-hewn churches, which date back to the Paleolithic period. The Sassi district of Matera consists of ancient stone dwellings carved into the limestone cliffs, forming one of the world’s oldest continuously inhabited settlements.` },

  // POIs for user2
  { 
    username: "user2", 
    description: `City of Verona - Verona is renowned for its well-preserved Roman heritage and its association with Shakespeare's famous tragedy "Romeo and Juliet." The city boasts a remarkable Roman amphitheater, known as the Arena di Verona, which is still used for opera performances. The town's charm also lies in its medieval and Renaissance architecture, with narrow streets, beautiful piazzas, and iconic landmarks such as Juliet’s house with the famous balcony.`
  },
  { 
    username: "user2", 
    description: `Late Baroque Towns of Val di Noto - This UNESCO World Heritage site comprises several towns in southeastern Sicily, including Noto, Modica, Ragusa, and others, rebuilt in the late 17th and early 18th centuries following the devastating earthquake of 1693. The towns are renowned for their magnificent Baroque architecture, characterized by ornate facades, intricate carvings, and expansive public squares, making them a spectacular example of late Baroque urbanism.`
  },
  { 
    username: "user2", 
    description: `Medici Villas and Gardens in Tuscany - The Medici Villas, a series of Renaissance-era villas scattered throughout Tuscany, showcase the Medici family's power and wealth during the Renaissance period. These villas are celebrated for their architectural grandeur and their stunning gardens, designed to represent the harmony between nature and human creativity. Notable villas include Villa di Castello and Villa La Petraia, which boast lush gardens and exquisite frescoed interiors.`
  },
  { 
    username: "user2", 
    description: `Mount Etna - Mount Etna is Europe’s highest and most active volcano, located on the eastern coast of Sicily. It is one of the most studied volcanoes in the world due to its frequent eruptions and its impact on the surrounding environment. Etna is a significant geological and cultural site, with ancient lava flows, craters, and rich biodiversity. It is also a popular destination for skiing in winter and hiking throughout the year.`
  },
  { 
    username: "user2", 
    description: `Costa dei Trabocchi - Among the most beautiful trabocchi are those of Punta Penna. Leave the state road and head towards the port, not forgetting to make a stop at the Punta Aderci Nature Reserve, with its sandy beach and promontory. Once again on the S.S.16, immediately after Casalbordino, you arrive at the coast of Torino di Sangro, famous for the Punta Le Morge overflow, easily reached from the beach. The journey continues from Fossacesia Marina to San Vito Marina, along a rugged coastline characterised by bays, coves and beaches. In Fossacesia, you can visit the Pesce Palombo trabocco and Punta Rocciosa. In Rocca San Giovanni, on the other hand, there are the Punta Cavalluccio, Punta Tufano, Punta Isolata, Sasso della Cajana and Punta Punciosa trabocchi`
  },
  { 
    username: "user2", 
    description: `Porticoes of Bologna - Bologna is famous for its medieval porticoes—an extensive network of covered walkways that line the streets of the city, providing shelter from the elements. These arcades stretch over 38 kilometers, making them one of the longest covered walkways in the world. The porticoes not only add to the city’s historic charm but also provide functional spaces, offering shelter and fostering a unique pedestrian-friendly environment.`
  },
  { 
    username: "user2", 
    description: `Piazza del Duomo, Pisa - The Piazza del Duomo, also known as the Field of Miracles, is home to Pisa's most famous landmark, the Leaning Tower of Pisa. This stunning ensemble of architectural masterpieces includes the cathedral, the baptistery, and the Camposanto Monumentale, all of which are exquisite examples of Romanesque and Gothic architecture. The site’s beauty and historical significance make it one of Italy’s most visited tourist destinations.`
  },
  { 
    username: "user2", 
    description: `Historic Centre of Siena - Siena is a medieval city in Tuscany that preserves its historical charm, with narrow streets, ancient buildings, and stunning public squares. The city is best known for the Palio, a centuries-old horse race held in the main square, Piazza del Campo. Siena is also famous for its Gothic architecture, especially the Siena Cathedral (Duomo), which boasts a magnificent interior and beautiful sculptures by renowned artists.`
  },
  { 
    username: "user2", 
    description: `Historic Centre of San Gimignano - San Gimignano is a small medieval town in Tuscany, famous for its well-preserved towers that define its skyline. The town has been nicknamed "The Manhattan of the Middle Ages" due to the 14 towers, which were built by wealthy families in the 12th and 13th centuries. In addition to the towers, the historic center is full of medieval buildings, palaces, and churches, making it a stunning example of medieval urban planning.`
  },
  { 
    username: "user2", 
    description: `Historic Centre of Pienza - Pienza is a small town in Tuscany that embodies Renaissance humanist urban planning. Commissioned by Pope Pius II, Pienza was transformed from a medieval village into a Renaissance gem by architect Bernardo Rossellino. The town's layout is based on the principles of ideal city design, with wide, scenic streets, charming piazzas, and elegant buildings such as the Palazzo Piccolomini. The town is also famous for its Pecorino cheese, which is produced locally.`
  },
  

  // POIs for user3
  { username: "user3", description: `Villa Adriana (Tivoli) - Constructed in the 2nd century AD as a retreat for Emperor Hadrian, Villa Adriana is an expansive complex that spans over 120 hectares, surpassing the size of Pompeii. The villa comprises more than 30 monumental structures, including palaces, baths, libraries, theaters, and extensive gardens adorned with fountains and sculptures. Hadrian's design reflects a synthesis of architectural elements from classical antiquity and Hellenistic traditions, showcasing his appreciation for diverse cultures.` },
  { username: "user3", description: `Villa d’Este, Tivoli - Established in the 16th century by Cardinal Ippolito II d'Este, Villa d’Este is renowned for its exquisite Renaissance gardens. The estate features an elaborate system of 51 fountains, 398 spouts, 364 water jets, 64 waterfalls, and 220 basins, all operating solely through gravity without the use of pumps. Notable fountains include the Hundred Fountains and the Fountain of the Organ, exemplifying the era's advanced hydraulic engineering and artistic design.` },
  { username: "user3", description: `Castel del Monte - Built in the 13th century by Emperor Frederick II near Bari, Castel del Monte is distinguished by its unique octagonal shape and the harmonious blend of architectural elements from classical antiquity, the Islamic Orient, and northern European Gothic styles. Each of the castle's eight corners features an octagonal tower, and the structure's precise geometric design reflects Frederick's interest in mathematics and astronomy. The castle's purpose remains a subject of intrigue, adding to its enigmatic allure.` },
  { username: "user3", description: `The Trulli of Alberobello - Located in the Puglia region, the Trulli are traditional limestone dwellings characterized by their conical roofs, constructed without mortar using a dry-stone technique. This architectural style dates back to the 17th century and is unique to the Itria Valley. The town of Alberobello boasts the highest concentration of these structures, which have been designated as a UNESCO World Heritage Site for their cultural significance and distinctive construction.` },
  { username: "user3", description: `National Park of Abruzzo, Lazio and Molise - Established in 1923, this park is one of Italy's oldest and is renowned for its rich biodiversity. It serves as a sanctuary for the critically endangered Marsican brown bear, with an estimated population of about 40 individuals. The park's diverse habitats also support species such as the Apennine wolf, Abruzzo chamois, and a variety of bird species, making it a vital area for wildlife conservation and ecotourism.` },
  { username: "user3", description: `Rocca Calascio - Perched at an elevation of approximately 1,460 meters (4,790 feet), Rocca Calascio is one of the highest fortresses in the Apennines. Constructed in the 10th century, the fortress was primarily intended for military purposes and offers commanding panoramic views of the surrounding mountains and valleys. Its strategic location and well-preserved ruins make it a significant historical and architectural landmark.` },
  { username: "user3", description: `Santo Stefano di Sessanio - This fortified medieval village is situated at 1,250 meters above sea level within the Gran Sasso and Monti della Laga National Park. Known for its well-preserved architecture, the village has undergone extensive restoration efforts to maintain its historical integrity. Narrow stone streets, ancient buildings, and surrounding natural beauty contribute to its charm, attracting visitors interested in history and cultural heritage.` },
  { username: "user3", description: `Sulmona - Nestled in the heart of Abruzzo, Sulmona is celebrated as the birthplace of the Roman poet Ovid and for its production of "confetti," the traditional sugared almonds associated with Italian celebrations. The town's historic center features medieval and Renaissance architecture, vibrant piazzas, and hosts annual jousting festivals that reenact medieval tournaments, reflecting its rich cultural traditions.` },
  { username: "user3", description: `Scanno - This picturesque medieval village is renowned for its stone houses, winding alleys, and proximity to Lake Scanno, a heart-shaped lake nestled among the mountains. The lake's unique shape and the village's charming atmosphere make it a favored destination for photographers and nature enthusiasts seeking scenic beauty and tranquility.` },
  { username: "user3", description: `Chieti - An ancient city with roots tracing back to pre-Roman times, Chieti is home to the National Archaeological Museum of Abruzzo, housed in the neoclassical Villa Frigerj. The museum's extensive collection includes artifacts from the region's early inhabitants, such as the Vestini and Marrucini tribes, and features notable exhibits like the Warrior of Capestrano, providing insights into the area's rich historical and cultural heritag.` },

  // POIs for user4
  { username: "user4", description: `Atri - Atri is renowned for the Cathedral of Santa Maria Assunta, a 13th-century Romanesque-Gothic cathedral built atop ancient Roman baths. Visitors can view remnants of these baths through glass panels in the cathedral floor. The town's elevated position offers panoramic views of the surrounding hills and Adriatic Sea.` },
  { username: "user4", description: `Lanciano -Lanciano is famed for the Eucharistic Miracle of Lanciano, dating back to the 8th century. According to tradition, a monk experiencing doubts witnessed the transformation of bread and wine into flesh and blood during Mass. These relics are preserved in the Church of San Francesco. The town also boasts a well-preserved medieval district with narrow streets and historic architecture.` },
  { username: "user4", description: `Ortona - Ortona, a coastal town, is home to the Cathedral of San Tommaso Apostolo, which houses the relics of Saint Thomas the Apostle. The cathedral, originally built over a pagan temple, was reconstructed after World War II due to significant damage. Ortona also played a pivotal role during WWII, notably in the Battle of Ortona, leading to its nickname "Western Stalingrad".` },
  { username: "user4", description: `Pescocostanzo - This charming town is celebrated for its well-preserved Renaissance and Baroque architecture. Pescocostanzo is also renowned for traditional crafts, particularly lace-making, with the Tombolo Lace School and Museum showcasing intricate lacework. The town's historic center features stone buildings and narrow streets reflecting its rich artisanal heritage.` },
  { username: "user4", description: `L’Aquila - As the capital of Abruzzo, L’Aquila boasts a rich medieval heritage. The city is encircled by 5.5 km of medieval walls and features numerous historic buildings and churches. Following the devastating 2009 earthquake, extensive restoration efforts have been underway to preserve and restore its architectural treasures.` },
  { username: "user4", description: `Celano - Dominated by the imposing Piccolomini Castle, constructed in the late 14th century, Celano overlooks the Fucino plain. The castle houses art and archaeological exhibits. Nearby, the Gorges of Celano offer a scenic 5 km trek through narrow canyons, attracting nature enthusiasts and hikers.` },
  { username: "user4", description: `Civitella del Tronto -This town is home to one of Europe's largest fortresses, the Fortezza di Civitella del Tronto, spanning over 25,000 square meters. Perched atop a rocky cliff at 600 meters above sea level, the fortress played a significant role in military history, serving as a strategic defensive structure .` },
  { username: "user4", description: `Guardiagrele - Known as the "stone city," Guardiagrele is famed for its Gothic Church of Santa Maria Maggiore and its tradition of metalwork artisanship, particularly in wrought iron and goldsmithing. The town offers stunning views of the Maiella mountain range and is recognized for its cultural and artistic heritage.` },
  { username: "user4", description: `Bominaco - Bominaco hosts the Oratory of San Pellegrino, often referred to as the "Sistine Chapel of Abruzzo" due to its extensive and well-preserved 13th-century frescoes depicting biblical scenes. Adjacent to it is the Church of Santa Maria Assunta, showcasing Romanesque architecture.` },
  { username: "user4", description: `Castelli - Celebrated for its traditional maiolica pottery, Castelli has been a center of ceramic production since the Renaissance. The town is home to the Church of San Donato, whose ceiling is adorned with 780 hand-painted ceramic tiles, earning it the nickname "Sistine Chapel of Maiolica".` },

  // POIs for user5
  { username: "user5", description: `Penne - A historic hill town in Abruzzo, Penne is known for its well-preserved medieval center with narrow alleys, Romanesque churches, and Renaissance-era palaces. It sits between the Adriatic coast and the Gran Sasso mountains, serving as a gateway to the Gran Sasso and Monti della Laga National Park. Nearby, the Lake Penne Nature Reserve offers opportunities for birdwatching, hiking, and nature tourism.` },
  { username: "user5", description: `Teramo - Teramo combines ancient Roman ruins with elegant Renaissance and Baroque architecture. The city features a Roman amphitheater and theater, a 12th-century cathedral with Gothic and Romanesque elements, and a vibrant old town filled with cafes and boutiques. Its mix of archaeological heritage and cultural vitality makes it a unique destination in northern Abruzzo..` },
  { username: "user5", description: `Giulianova - Giulianova is a coastal town with two distinct areas: a modern seaside resort with sandy beaches and a charming old town on the hill. The Sanctuary of the Madonna dello Splendore, surrounded by gardens and fountains, is a key religious site offering sea views and housing a museum of sacred art. Giulianova blends seaside relaxation with spiritual and historical depth..` },
  { username: "user5", description: `Vasto - Overlooking the Adriatic Sea from a scenic cliff, Vasto features a historic center rich with medieval and Renaissance architecture, including the Caldoresco Castle and the Cathedral of San Giuseppe. The town offers access to some of Abruzzo’s best beaches and natural sites like Punta Aderci, a coastal reserve with dunes, cliffs, and marine life..` },
  { username: "user5", description: `Pietracamela - Nestled on the slopes of the Gran Sasso mountains, Pietracamela is a picturesque mountain village known for its stone houses, narrow lanes, and alpine traditions. It’s a popular base for hikers and climbers heading toward Corno Grande and Corno Piccolo. The village is part of the Gran Sasso and Monti della Laga National Park and is listed among Italy’s most beautiful villages..` },
  { username: "user5", description: `Navelli - Navelli is a peaceful medieval village set on a plateau, famous for producing high-quality saffron known as “red gold.” The village’s historic stone buildings, cobbled streets, and surrounding fields of crocus flowers offer a glimpse into rural Abruzzese life. Every fall, Navelli hosts a saffron festival celebrating its centuries-old agricultural heritage..` },
  { username: "user5", description: `Abruzzo - The history of Abruzzo is long and fascinating, especially that concerning its origins. The most widely accepted hypothesis is that Abruzzo derives from Aprutium, a popular evolution of (ad)Praetutium, the land of the Pretuzi, an ancient Italic population that lived in what is now Teramo.Populated since prehistoric times, the region was home to groups of shepherds, all belonging to the Samnite lineage, who exploited the natural roads created in the long valleys for the transhumance of sheep: they travelled along mountain roads and gorges from the areas around L'Aquila to Foggia and back. Transhumance was the territory's main means of economic support.Among the populations that marked the territory were the Marsi, the Peligni, the Vestini, and the Equi, who lived in walled cities with large sanctuaries. On the subject of the Vestini, and the Samnite wars, we still have a precious testimony today: the statue of the Capestrano Warrior, a soft limestone sculpture depicting one of their warriors. It is one of the most monumental and significant works of Italic art now preserved in Chieti. ` },
  { username: "user5", description: `Pescasseroli - Pescasseroli è adagiata in una conca all'ingresso dell'Alta Valle del Sangro a m. 1167 sul livello del mare. Questo altopiano ricco di pascoli è circondato da boschi centenari e montagne suggestive. Pescasseroli è un paese in cui è evidente la simbiosi tra natura ed architettura: il centro abitato è in perfetta armonia con le meraviglie naturali che lo circondano. Il nucleo urbano, in posizione pianeggiante, si è sviluppato attorno all'antica abbazia ed è caratterizzato da tradizionali costruzioni in muratura di pietrame e malta, adornate dalle particolari finestre con imbotti in pietra da taglio locale, denominata "pietra gentile" dal nome dell'omonima montagna. La piazza S.Antonio, così chiamata per la presenza di una chiesa oggi scomparsa, è il fulcro della vita di Pescasseroli: è colorata dai faggi e profumata dai piccoli fiori dei tigli ed è ornata, oltre che dalla sede del Comune, da una graziosa fontana, sormontata da una statuetta dell'Immacolata.
    Curiosità:
    Il nome Pescasseroli sembra derivare da "Pesculum Serulae", cioè roccia sorgente a picco (dal tardo latino "pensulum"), o masso che serra; secondo Benedetto Croce, "Pesculum ad Sorolum", cioè masso presso il piccolo Sangro (le sorgenti). La parte più antica dell'abitato sorge ai piedi dello sperone roccioso «pesco», su cui si trovano i resti di «Castel Mancino». Nella leggenda marsicana il poeta pastore Cesidio Gentile fa derivare la fondazione di Pescasseroli dalla vicenda drammatica di un giovane cavaliere crociato, Serolo, figlio del Conte Maracino, signore del castello. Serolo, partecipando alla I Crociata, incontra in Palestina la bella saracena Pesca, della quale si innamora e che sposa. In compagnia di un santo anacoreta, che aveva con sè la statuina lignea della Madonna nera, Pesca viene mandata da Serolo al castello. Una volta al castello, il vecchio Conte si invaghisce, non ricambiato, di Pesca che, fuggendogli, viene raggiunta ed uccisa in prossimità di una sorgente (quel posto è da allora chiamato «malafede»). Tornato dalla Crociata ed appresa la morte cruenta della sua sposa, Serolo muore di dolore. Sulla tomba dei due giovani sposi il vecchio Conte, in espiazione del delitto, fonda il paese che chiama Pescasseroli dall'unione dei due nomi.
    Manifestazioni:
    Festa dei SS. Pietro e Paolo (29-30/6); festa della Madonna dei Carmelo (15-16/7); Madonna di Monte Tranquillo (ultima domenica di luglio); festa della Madonna Incoronata (8-9/9).Usi e costumi:E' un'antica usanza tostare e aromatizzare i ceci con la sabbia prima delle nozze. Il costume tradizionale femminile di Pescasseroli, di istituzione relativamente recente, è tutto in nero, mentre quello antico era sfarzoso e vivace. Il costume nero fu introdotto nell'uso per una circostanza del tutto fortuita: si racconta che nel 1846 alcune donne di Pescasseroli che si recavano ad Ischia per delle cure termali furono oggetto, a Napoli, di curiosa e indiscreta attenzione. Le donne trovarono rifugio a Procida ove scambiarono i loro costumi con quelli delle donne locali.Tornate a Pescasseroli i nuovi costumi piacquero tanto da essere adottati da tutte le donne.
  astronomia:
    Agnello al cotturo, patate maritate, dolce fritto natalizio, detto 'trcnell', "la P'plla" (tipico dolce Pasquale).` },
  { username: "user5", description: `Gran Sasso and Monti della Laga National Park– A large territory, with peaks that touch the sky and rich vegetation to protect ancient villages, hermitages and castles, among centuries-old chestnut trees and boundless seasonal blooms.Covering an area that includes three regions, Abruzzo, Lazio and Le Marche, the Park is a very complex area, divided into two distinct biogeographical regions: "Euro-Siberian" and "Mediterranean". The morphological diversity of the mountains and the high altitudes they reach make this protected area a treasure of exceptional biological richness. From the remains of the glaciers at high altitudes, to the vastness of the plains of Campo Imperatore at the foot of Corno Grande, as far as the almond trees, vineyards and olive groves further down the valley, the scenery offered by the Park goes on forever. Silent, except when flowing over jumps and waterfalls, the Tirino (the river with some of the clearest water in Europe!) is another central element of the Park: the local flora and fauna draw all the energy they need to flourish along its banks. In addition to the Tirino, several rivers and streams run through the park, bringing their energy and vitality.` },
  { username: "user5", description: ` Campotosto Lake Nature Reserve– The largest artificial lake in Abruzzo Created in 1984 and spanning an area of 1,600 hectares, the Campotosto Lake Nature Reserve is a protected area in the province of L’Aquila. The area boasts the largest artificial lake in the region and falls within the Gran Sasso and Monti della Laga National Park.  
The reserve is an important migratory site for many animal species, some of which are endangered. The lake shore is home to the grey heron, the common shelduck, the common snipe, the great snipe—the star of the protected area—and Abruzzo’s largest colonies of common pochard and wigeon. Trout and tench are the most common fish species. The lake is very popular in the summer season among jogging and trekking enthusiasts, as well as for sport fishing, canoeing and windsurfing, while in winter it is not uncommon to find it partially or completely frozen over. The almost flat lakefront, 40 kilometres long, is a popular destination for cycling and mountain biking. Around the reserve, sport enthusiasts can find the Capannelle pass, the go-to place for motorcyclists, and the ski resorts of Campo Imperatore and Prati di Tivo. The lake is also connected to the tourist itineraries of the Horse Riding Trail of Gran Sasso and the Park’s main road.` },

  // POIs for user6
  { username: "user6", description: `Opi – Situato in uno splendido anfiteatro naturale, circondato da rigogliose montagne ricche di boschi, Opi conserva ancora oggi le caratteristiche di antico borgo medioevale, singolare per la posizione e l'aspetto di grande interesse archeologico. La presenza umana nel territorio di Opi ha origini remote, ne sono testimonianza i resti di un centro fortificato nel luogo in cui sorge l'attuale abitato, i tanti reperti archeologici rinvenuti nella Necropoli di Val Fondillo e i resti di un probabile tempio nelle località "Casali" e "Fonte delle Lecina".
Curiosità:
Il giorno di Sant'Antonio Abate si rinnova lo scambio dei 'cicciotti', un miscuglio di grano, fave secche, ceci e mais lessati.
Manifestazioni:
Il 24-25 giugno si festeggiano San Giovanni Battista e San Vincenzo Ferreri, patroni e protettori di Opi. La seconda domenica di settembre si festeggiano S.Emidio e la Madonna delle Grazie, mentre la prima domenica di ottobre S.Teresa e la Madonna del Rosario. La notte di Natale, dopo la santa messa, ci si ritrova in piazza della chiesa dove viene acceso un grande falò, detto "i catozze", in onore di Gesù Bambino. Il 17 gennaio si festeggia S.Antonio, giorno in cui i contadini usano far crociare i propri animali.
In agosto si svolge la Sagra degli gnocchi, una grande festa realizzata grazie alla partecipazione di molti turisti che affollano i tavoli, appositamente allestiti dalla Pro Loco per gustare gli gnocchi accuratamente preparati dalle massaie del paese.
Usi e costumi:
'Catozze', fuoco acceso la notte di Natale.
Gastronomia:
"m'paniccia", pecora al cotturo, "m'cisca" carne di pecora essiccata, frittelle di cavolfiore; cicatelli con le foglie; ricotta e pecorino. Dolci: tanozzi, torroncini, sanguinacci con riso, cicirchiata.` },
  { username: "user6", description: `Civitella Alfedena –Il turista che visita Civitella per la prima volta resta subito affascinato dalle forme graziose ed armoniose dell'architettura, che lascia intravedere ancora case in pietra e vicoli strettissimi in cui "perdersi" durante una passeggiata all'insegna della tradizione.
Sorge alle pendici del Monte Sterpi d'Alto, che rappresenta solo l'inizio di quel meraviglioso spettacolo che si apre subito alle spalle del grazioso borgo: l'anfiteatro della Camosciara (Zona di Riserva Integrale del Parco). Ai piedi del paesino, il Lago di Barrea, facilmente raggiungibile con una passeggiata pedonale che attraversando la Pineta porta al Ponte Vecchio e quindi sulle sponde del lago.

Curiosità:
Botteghe di artigianato. Fiaccolata di fine anno (30 dicembre) dal Monte Mava;
Presepe di carta pesta.

Manifestazioni:
Festa di Santa Lucia (seconda domenica di luglio); feste di San Nicola e Madonna del Carmine; sagra della "scrupella" (dolce fritto).

Usi e costumi: Artigianato tipico con tessitura a mano, pittura su ceramica, produzione di miele.

Gastronomia: Zuppe locali e dolci di mandorle. ` },
  { username: "user6", description: `InfoPoint del Parco Nazionale d'Abruzzo, Lazio e Molise – Visitor Support Hubs The InfoPoint facilities of the National Park serve as essential visitor support hubs, offering information on trails, wildlife, park regulations, and cultural attractions. Many are equipped with exhibits, educational materials, and maps, helping visitors plan their activities while promoting responsible tourism and conservation awareness.` },
  { username: "user6", description: ` InfoPoint Pro Loco Opi– La Pro Loco Opi – APS è stata costituita nella Primavera del 1976, iscritta all'Albo Regionale delle Pro Loco con DPGR al n.25 del 9 febbraio del 1977, fa parte dell'Unione Nazionale Pro Loco d'Italia (UNPLI).
È un'Associazione di interesse pubblico, apartitica, senza fini di lucro, volta alla promozione e alla tutela del territorio a 360°; ritiene infatti fondamentale, offrire al turista, un'immagine di Opi intesa come unicum assoluto, in cui ogni giorno armonicamente si fondono i vari aspetti turistico, culturale, naturalistico, storico, sociale ed eno-gastronomico.
La mission della Pro Loco di Opi – APS è riuscire a coniugare la tutela e la salvaguardia delle specialità locali con la vocazione allo sviluppo della crescita sociale ed al miglioramento del benessere.
I valori ispiranti dell'agire dalla Pro Loco Opi – APS sono il volontario, la collaborazione, la creazione di valore per la comunità, l'essere “luogo” di relazioni umane e sociali, tutto “a favore del territorio”, in collaborazione e in sinergia con altri enti e organizzazioni.
Per il conseguimento delle proprie finalità la Pro Loco di Opi – APS:
Promuove la cultura dell'accoglienza e dell'informazione turistica curando l'Ufficio Turistico, aperto durante tutto l'anno.
Contribuisce al miglioramento della qualità della vita del Comune, sia per i cittadini, sia per i turisti; offre appoggio logistico ad altre Associazioni e a tutti i cittadini di Opi, mettendo a disposizione fotoriproduttori, pc con stampante, servizio telefax, collegamento Wi-Fi con postazioni internet point.
Sviluppa attività di carattere sociale: è affidataria della biblioteca comunale, ricca di libri sulla flora e sulla fauna del Parco d'Abruzzo e sui tesori architettonici, gestisce il museo “C'era una volta..I Mestieri”, “C'era una volta..Trasuta e Sposa” e il Museo dello Sci.
Promuove eventi culturali, organizza convegni, corsi didattici, concerti, visite guidate e manifestazioni.` },
  { username: "user6", description: `InfoPoint Territoriali – In addition to the main park centers, several local InfoPoints operate across the territory, providing community-level guidance on local attractions, hiking trails, accommodation, and cultural events. These services help deepen the visitor's connection to each town while supporting local economies.` },
  { username: "user6", description: `Area Faunistica del Lupo – L'area Faunistica del Lupo appenninico è un'aea naturale, recintata e adiacente al paese, istituita per scopi scientifici (ripopolamento e studio) dal Parco Nazionale d'Abruzzo, Lazio e Molise; essa offre la possibilità di avvistare lupi e linci in semilibertà. L'itinerario di visita, molto semplice, porta ad osservare alcuni lupi in semi libertà, il Lago di Barrea, una grande quercia e un bosco di conifere con presenza di pino nero. Presso il Museo del lupo è possibile acquistare il pieghevole illustrativo di questo facile sentiero natura. Il percorso natura parte accanto al Museo del Lupo, sulla via con i selci neri, che sale al piazzale Santa Lucia. La strada si affaccia sulla destra, sull'area faunistica del Lupo appenninico, in un pannello illustrativo sono riportate delle notizie su questo magnifico predatore.
     Con un po' di attenzione e facile scorgere alcuni esemplari di questo animale sopra la collina che domina la riserva. Raggiunta la sommità, si ha un bel panorama sul Lago di Barrea, il piazzale offre invece, una veduta classica del borgo di Civitella Alfedena. Su di un lato della grande piazza, c'è il “capannino” del Parco, composto di pannelli illustrativi sui sentieri escursionistici dell'area protetta. Al centro, accanto alla piccola fontana, vi è una grande pianta di tiglio, che fiorisce in primavera. Fino a pochi anni or sono, le donne del paese vi si recavano a raccogliere i fascetti odorosi per farne delle tisane. Poco più in la, una grande guercia secolare (cerro) è invece posta davanti alla chiesa di S. Lucia. La chiesa anche se da poco rifatta, conserva una struttura a croce greca, che la lega all'antica storia religiosa dei maroniti che vi giunsero dal lontano Libano. Due monaci maroniti del VIII sec., Barnam e Josaphat, raffigurati in due statue di legno, opera di scalpellini napoletani,  sono poste  dentro la chiesa, accanto alla statua cinquecentesca di S. Lucia. Sul lato del piccolo campanile, un'apertura porta sul viottolo che cala attraverso il bosco di conifere (alberi di pino nero e abete rosso), piantati all'inizio del 1900 dai bambini di Civitella su iniziativa di un maestro elementare). Poco dopo, lasciando la discesa,  si prosegue a destra per arrivare dietro la chiesa, dove si trova un'area attrezzata per il pic nic. Salendo la piccola dorsale del colle con rose selvatiche, prugnoli e maggiociondoli, si giunge alla palina N. 9. Si riprende poi il sentiero che poco più avanti scende sulla destra, superate alcune rocce di natura calcarea, colonizzate da muschi e licheni, alla fine del bosco si raggiunge nuovamente la stradina selciata. Voltando a destra in salita e costeggiando sulla sinistra l'area recintata del Lupo, si torna al punto di partenza.` },
  { username: "user6", description: `Area Faunistica del Cervo – Situata a 1500 m. di quota, nei pressi del Centro Informazioni di Gamberale, l'area faunistica è stata realizzata su terreni di proprietà del Comune di Gamberale (CH) siti nel Comune di Ateleta (AQ), in località Laghetto S. Antonio. L'area faunistica del cervo nasce nel 2003 con animali provenienti da altre aree faunistiche e centri di recupero; la notevole estensione dell'area, oltre 10 ettari e la presenza di vaste porzioni di aree di bosco, cespuglieti e pascoli, oltre che corsi d'acqua naturali, contribuisce a rendere le condizioni di vita degli animali ospitati molto vicine a quelle dei cervi a vita libera presenti in diversi settori del Parco.
Gli animali sono facilmente avvistabili e da metà settembre a fine ottobre, è possibile ascoltare le vocalizzazioni, i cosiddetti bramiti, che i maschi adulti di cervo emettono nel periodo riproduttivo. Attualmente l'area ospita sedici esemplari di cervo.
Come tutte le aree faunistiche del Parco, anche l'area faunistica del cervo costituisce un notevole elemento di sensibilizzazione nei confronti dei turisti, delle scolaresche e della popolazione residente.
Nei pressi dell'area, all'interno del bosco di faggio, è presente un percorso ad anello accessibile ai diversamente abili di particolare valenza naturalistica.` },
  { username: "user6", description: `Area Faunistica dell’Orso – L'Area Faunistica dell'Orso è stata inaugurata il 18 settembre 2010 e si trova a Campoli Appennino (FR), paese del Parco Nazionale d'Abruzzo Lazio e Molise (PNALM) a circa 7 km da Sora.

Il paese di Campoli, nella conformazione attuale, ha origine medioevale (come testimoniano la Torre ed i resti delle mura di fortificazione), sorge a 650 m s.l.m., conta una popolazione di circa 1700 abitanti ed ha la particolarità di svilupparsi interamente intorno a un'estesa dolina - localmente chiamata "Fossa" o "Tomolo" - manifestazione del fenomeno carsico particolarmente diffuso nell'Appennino centrale. Nella sua forma sub-ellittica, si estende per 630×400 m, ed ha una profondità di 130 m, con la caratteristica di avere i versanti esposti a Nord e Sud di differente età geologica.

Questo piccolo borgo dell'Appennino laziale-abruzzese - già conosciuto per il suo celebre e raffinato tartufo, apprezzato a livello nazionale e internazionale - grazie all'istituzione dell'Area Faunistica si è meritato l'appellativo di "Città dell'Orso e del Tartufo" come recita un pannello di accoglienza posto all'entrata del paese.

Il territorio comunale campolese per buona parte si trova nella cosiddetta zona di protezione esterna del Parco Nazionale d'Abruzzo Lazio e Molise. Una porzione della sua superficie, anche se di minore estensione, rientra entro i confini veri propri del Parco: è perciò possibile ammirarne tutt'intorno il magnifico paesaggio, fatto di vette mozzafiato ed estesi boschi.

La ricchezza naturalistica di Campoli - praticamente incontaminata - lo ha reso da sempre un luogo privilegiato per poter osservare la fauna tipica del Parco che spesso si spinge fino ai limiti del centro abitato. L'orso, che ne è l'elemento più rappresentativo, non fa eccezione e in qualche caso non disdegna delle inaspettate visite a "domicilio" ai paesani.` },
  { username: "user6", description: `Centro Visita dell’Orso – Nel cuore del Parco nazionale D'Abruzzo Lazio e Molise, nello splendido borgo di Villavallelonga a 1005 metri d'altezza, sorge il Centro Visita dell'Orso di Villavallelonga. Struttura del Parco, il Centro visite nasce con finalità educativa ed informativa incentrata sulla figura del plantigrado simbolo del Parco, l'Orso Bruno Marsicano.
Museo dell'Orso - Il percorso museale illustra la vita di questo famoso plantigrado attraverso pannelli, bacheche e diorami; periodicamente vengono ospitate mostre temporanee. Ai piccoli visitatori è dedicato un punto di interpretazione della natura e nella sala proiezioni annessa è possibile assistere a filmati naturalistici generali o specifici sulla vita e le abitudini dell'Orso.
Postazione 3D - attraverso un video naturalistico in 3D il visitatore conosce da vicino la fauna del Parco, in compagnia dell'orso, del lupo e dei tanti animali che abitano il territorio.
Ufficio Informazioni - Situato all'ingresso del museo, personale specializzato nel servizio di front office fornisce indicazioni e assistenza per la partecipazione alle attività di educazione ed animazione ambientale, sul programma di escursioni e sulle modalità d'iscrizione alle varie attività.
Area Faunistica e Sentiero Natura - Percorrendo il Sentiero Natura attrezzato si scorge l'ampia area recintata che ospita in stato di semilibertà un esemplare di Orso Bruno Marsicano.
Area shop ed esposizione prodotti locali - nella struttura è presente un'area shop per l'acquisto di souvenirs e materiale didattico e scientifico sul Parco nazionale d'Abruzzo, Lazio e Molise. Per chi vuole conoscere il territorio attraverso l'artigianato e l'enogastronomia locale è allestito inoltre uno spazio di esposizione di prodotti tipici locali artigianali ed enogastronomici.
Area pic-nic - Nell'area adiacente il Museo sono inoltre presenti 3 aree picnic all'aperto.` },
  { username: "user6", description: `Sala dei Pipistrelli – Located in Barrea, this exhibit space is dedicated to the study and appreciation of bats. Visitors can explore displays with photos, books, and videos, and even watch a live stream of a nearby bat colony. It’s a unique way to educate the public about the ecological importance of bats and challenge common myths.` },

  // POIs for user7
  { username: "user7", description: `Percorso Espositivo sull’Orso – This educational exhibit is dedicated to the natural history of the Marsican brown bear and its relationship with humans. It offers insights into the bear's biology, behavior, and the cultural significance it holds in the region. Through interactive displays and informative panels, visitors can learn about conservation efforts and the importance of coexistence between bears and local communities.` },
  { username: "user7", description: `Museo della Transumanza – The Museum of Transhumance, located within the Caseificio Di Nucci, offers a unique experience combining history, emotion, and taste. It showcases wooden tools, ancient books, and modern artworks that narrate the story of a family dedicated to cheese-making for centuries. Visitors can engage in educational activities, guided tastings of local products, and explore the rich pastoral heritage of the region.` },
  { username: "user7", description: `Museo Civico Archeologico A. De Nino – Alfedena’s Samnite Heritage - Located near the necropolis of Campo Consolino, this museum houses precious archaeological finds...` },
  { username: "user7", description: `InfoPoint del Parco – Local Access to Protected Area Insights - The InfoPoint structures throughout the Abruzzo, Lazio and Molise National Park...` },
  { username: "user7", description: `InfoPoint CETS – European Charter for Sustainable Tourism - These special InfoPoints are managed by facilities that have committed to the European Charter for Sustainable Tourism (CETS)...` },
  { username: "user7", description: `InfoPoint CETS – Certified Sustainable Tourism Centers - Within the Abruzzo, Lazio and Molise National Park, select InfoPoints are managed by organizations that have embraced the CETS...` },
  { username: "user7", description: `InfoPoint Territoriali – Local Tourism Support Centers - These InfoPoints, managed by local municipalities and Pro Loco associations...` },
  { username: "user7", description: `Museo Nazionale d'Abruzzo – L'Aquila - Housed in the 16th-century Spanish Fort of L'Aquila, this national museum contains remarkable archaeological finds...` },
  { username: "user7", description: `Eremo di San Bartolomeo in Legio – Roccamorice - This hermitage is carved into a cliff in the Majella mountains and dates back to the 11th century...` },
  { username: "user7", description: `Abbazia di San Giovanni in Venere – Fossacesia - Overlooking the Adriatic coast, this 12th-century Benedictine abbey blends Romanesque and Gothic architecture...` },

  // POIs for user8
  { username: "user8", description: `Castello Piccolomini – Celano - This impressive 15th-century castle is perched on a hill and houses the Museum of Sacred Art of the Marsica...` },
  { username: "user8", description: `Museo delle Genti d'Abruzzo – Pescara - This museum tells the story of Abruzzo's people through centuries of culture, traditions, and crafts...` },
  { username: "user8", description: `Abbazia di Santo Spirito al Morrone – Sulmona - Once the residence of Pope Celestine V, this large monastic complex showcases baroque elements...` },
  { username: "user8", description: `Chieti Historic Center – Chieti - Among the oldest cities in Italy, Chieti’s center features Roman ruins, medieval churches, and elegant palaces.` },
  { username: "user8", description: `Museo Archeologico Nazionale di Campli – Campli - Known for its medieval architecture and Holy Staircase, Campli also hosts this archaeological museum...` },
  { username: "user8", description: `Civitella del Tronto Fortress – Teramo - One of the largest fortresses in Europe, this military complex was the last Bourbon stronghold to fall...` },
  { username: "user8", description: `Atri Cathedral and Diocesan Museum – Atri - The 13th-century cathedral is famous for its frescoes by Andrea de Litio...` },
  { username: "user8", description: `Castello Aragonese – Ortona - Overlooking the Adriatic Sea, this 15th-century castle was originally built for military defense...` },
  { username: "user8", description: `Museo Capitolare – Atri - This small yet rich museum is located next to the cathedral and contains liturgical treasures...` },
  { username: "user8", description: `Complesso di San Clemente a Casauria – Castiglione a Casauria - Founded in the 9th century, this abbey is a masterpiece of Romanesque art...` },

  // POIs for user9
  { username: "user9", description: `Museo del Costume e della Tradizione della Nostra Gente – Pollutri - A cultural museum preserving traditional Abruzzese clothing, tools, and rural life scenes...` },
  { username: "user9", description: `Museo della Ceramica – Castelli - Located in the heart of Italy’s ceramic tradition, this museum houses a valuable collection of maiolica pottery...` },
  { username: "user9", description: `Teatro Marrucino – Chieti - Built in 1818, this historic theater is one of the oldest in Abruzzo and hosts classical concerts...` },
  { username: "user9", description: `Eremo di San Domenico – Villalago - A tranquil hermitage near Lake San Domenico, it features a stone sanctuary built into the rock...` },
  { username: "user9", description: `Museo Naturalistico e Archeologico “Villa Badessa” – Rosciano - This museum explores both the natural environment and archaeological past of the region...` },
  { username: "user9", description: `Fontevecchia – Spoltore - A reconstructed 19th-century rural village experience where visitors can engage in traditional crafts...` },
  { username: "user9", description: `Museo dell'Olio di Loreto Aprutino – Loreto Aprutino - Set in a historic olive oil mill, this museum celebrates the region's centuries-old olive oil production...` },
  { username: "user9", description: `Museo della Civiltà Contadina – Penne - This museum preserves agricultural tools, domestic objects, and reconstructions of rural life...` },
  { username: "user9", description: `Palazzo Ducale – Tagliacozzo - A splendid example of Renaissance architecture, this palace once hosted nobles...` },
  { username: "user9", description: `Eremo di San Venanzio – Raiano - Built on a cliff over a gorge, this hermitage is accessible via a narrow footbridge...` },

  // POIs for user10
  { username: "user10", description: `Museo delle Arti e Tradizioni Popolari – L’Aquila - Located in the historic quarter of San Pietro di Coppito, this museum displays costumes...` },
  { username: "user10", description: `Museo Archeologico – Guardiagrele - A small museum highlighting local archaeological finds, including Roman inscriptions...` },
  { username: "user10", description: `Castello Cantelmo – Pettorano sul Gizio - This medieval fortress offers panoramic views of the Gizio Valley...` },
  { username: "user10", description: `Chiesa di Santa Maria del Lago – Moscufo - A Romanesque church known for its beautifully preserved frescoes...` },
  { username: "user10", description: `Museo Civico – Sulmona - Located in the Palazzo dell’Annunziata, this museum houses art collections, archaeological relics...` },
  { username: "user10", description: `Chiesa di San Pietro ad Oratorium – Capestrano - An 8th-century church famed for its Lombard-Romanesque architecture...` },
  { username: "user10", description: `Museo della Lana – Scanno - Housed in an old wool workshop, this museum highlights the textile traditions of Scanno...` },
  { username: "user10", description: `Convento di San Francesco – Castelvecchio Subequo - This convent dates back to the 13th century and holds artworks...` },
  { username: "user10", description: `Torre di Cerrano – Pineto - One of the ancient coastal watchtowers, now used as a sea and marine biology museum...` },
  { username: "user10", description: `Museo Paleontologico – Lettomanoppello - Dedicated to fossils and prehistoric life, this museum houses collections...` }
];
// === 🏷️ Extract Title from Description ===
samplePOIs = samplePOIs.map(poi => {
    const titleMatch = poi.description.match(/^(.+?)\s*[-–]\s*/);
    const title = titleMatch ? titleMatch[1].trim() : poi.description.split('.')[0];
    return {
      ...poi,
      title
    };
  });
const userPOICounters = {};
samplePOIs.forEach(poi => {
  const user = poi.username;
  if (!userPOICounters[user]) userPOICounters[user] = 0;
  poi.poiIndex = userPOICounters[user];
  userPOICounters[user]++;
});

// === 4. Clear + Insert ===
(async () => {
  try {
    await POI.deleteMany({});
    console.log('🧹 Existing POIs cleared.');

    await POI.insertMany(samplePOIs);
    console.log('✅ Sample POIs inserted successfully');

    mongoose.disconnect();
  } catch (err) {
    console.error('❌ Error:', err);
    mongoose.disconnect();
  }
})();

